2018-01-15 23:40:20	ewer	everwork.py - [<module>]	MainThread - 1068 - 3948	DEBUG: 程序结束！
2018-01-15 23:48:58	ewer	everfunc.py - [getapitimesfromlog]	MainThread - 2592 - 6048	INFO: log文进中还没有API的调用记录
2018-01-15 23:48:58	ewer	everwork.py - [<module>]	MainThread - 2592 - 6048	DEBUG: 程序启动……
2018-01-15 23:48:58	ewer	everwork.py - [<module>]	MainThread - 2592 - 6048	DEBUG: 配置文件读取成功
2018-01-15 23:48:58	ewer	everfunc.py - [wrapper]	MainThread - 2592 - 6048	DEBUG: get_notestore 启动运行
2018-01-15 23:49:00	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2592 - 6048	DEBUG: 动用了Evernote API 62 次……
2018-01-15 23:49:00	ewer	everfunc.py - [get_notestore]	MainThread - 2592 - 6048	DEBUG: 成功连接Evernote服务器！
2018-01-15 23:49:00	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2592 - 6048	DEBUG: 动用了Evernote API 63 次……
2018-01-15 23:53:06	ewer	everfunc.py - [<module>]	MainThread - 2752 - 3316	INFO: 程序上次异常退出，调用log中的API数据[2018-01-15 23:49:00,63]
2018-01-15 23:53:06	ewer	everwork.py - [<module>]	MainThread - 2752 - 3316	DEBUG: 程序启动……
2018-01-15 23:53:06	ewer	everwork.py - [<module>]	MainThread - 2752 - 3316	DEBUG: 配置文件读取成功
2018-01-15 23:53:06	ewer	everfunc.py - [wrapper]	MainThread - 2752 - 3316	DEBUG: get_notestore 启动运行
2018-01-15 23:53:07	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2752 - 3316	DEBUG: 动用了Evernote API 64 次……
2018-01-15 23:53:07	ewer	everfunc.py - [get_notestore]	MainThread - 2752 - 3316	DEBUG: 成功连接Evernote服务器！
2018-01-15 23:53:08	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2752 - 3316	DEBUG: 动用了Evernote API 65 次……
2018-01-15 23:54:24	ewer	everfunc.py - [<module>]	MainThread - 13900 - 5920	INFO: 程序上次异常退出，调用log中的API数据[2018-01-15 23:53:08,65]
2018-01-15 23:54:24	ewer	everwork.py - [<module>]	MainThread - 13900 - 5920	DEBUG: 程序启动……
2018-01-15 23:54:24	ewer	everwork.py - [<module>]	MainThread - 13900 - 5920	DEBUG: 配置文件读取成功
2018-01-15 23:54:24	ewer	everfunc.py - [wrapper]	MainThread - 13900 - 5920	DEBUG: get_notestore 启动运行
2018-01-15 23:54:26	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13900 - 5920	DEBUG: 动用了Evernote API 66 次……
2018-01-15 23:54:26	ewer	everfunc.py - [get_notestore]	MainThread - 13900 - 5920	DEBUG: 成功连接Evernote服务器！
2018-01-15 23:54:27	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13900 - 5920	DEBUG: 动用了Evernote API 67 次……
2018-01-15 23:54:27	ewer	everfunc.py - [writeini]	MainThread - 13900 - 5920	INFO: Evernote API调用次数：68，写入配置文件data\everwork.ini
2018-01-15 23:54:27	ewer	everwork.py - [<module>]	MainThread - 13900 - 5920	DEBUG: 程序结束！
2018-01-15 23:55:06	ewer	everwork.py - [<module>]	MainThread - 14740 - 6852	DEBUG: 程序启动……
2018-01-15 23:55:06	ewer	everwork.py - [<module>]	MainThread - 14740 - 6852	DEBUG: 配置文件读取成功
2018-01-15 23:55:06	ewer	everfunc.py - [wrapper]	MainThread - 14740 - 6852	DEBUG: get_notestore 启动运行
2018-01-15 23:55:07	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14740 - 6852	DEBUG: 动用了Evernote API 68 次……
2018-01-15 23:55:07	ewer	everfunc.py - [get_notestore]	MainThread - 14740 - 6852	DEBUG: 成功连接Evernote服务器！
2018-01-15 23:55:08	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14740 - 6852	DEBUG: 动用了Evernote API 69 次……
2018-01-15 23:55:08	ewer	everfunc.py - [writeini]	MainThread - 14740 - 6852	INFO: Evernote API调用次数：70，写入配置文件data\everwork.ini
2018-01-15 23:55:08	ewer	everwork.py - [<module>]	MainThread - 14740 - 6852	DEBUG: 程序结束！
2018-01-16 07:05:10	ewer	everfunc.py - [writeini]	MainThread - 5212 - 9772	INFO: Evernote API调用次数：0，写入配置文件data\everwork.ini
2018-01-16 07:05:10	ewer	everwork.py - [<module>]	MainThread - 5212 - 9772	DEBUG: 程序启动……
2018-01-16 07:05:10	ewer	everwork.py - [<module>]	MainThread - 5212 - 9772	DEBUG: 配置文件读取成功
2018-01-16 07:05:10	ewer	everfunc.py - [wrapper]	MainThread - 5212 - 9772	DEBUG: get_notestore 启动运行
2018-01-16 07:05:12	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5212 - 9772	DEBUG: 动用了Evernote API 0 次……
2018-01-16 07:05:12	ewer	everfunc.py - [get_notestore]	MainThread - 5212 - 9772	DEBUG: 成功连接Evernote服务器！
2018-01-16 07:05:16	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5212 - 9772	DEBUG: 动用了Evernote API 1 次……
2018-01-16 07:05:16	ewer	everfunc.py - [imglist2note]	MainThread - 5212 - 9772	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-16 07:05:17	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5212 - 9772	DEBUG: 动用了Evernote API 2 次……
2018-01-16 07:05:33	ewer	everfunc.py - [writeini]	MainThread - 5212 - 9772	INFO: Evernote API调用次数：3，写入配置文件data\everwork.ini
2018-01-16 07:05:33	ewer	everwork.py - [<module>]	MainThread - 5212 - 9772	DEBUG: 程序结束！
2018-01-17 12:51:06	ewer	everfunc.py - [writeini]	MainThread - 11912 - 14812	INFO: Evernote API调用次数：0，写入配置文件data\everwork.ini
2018-01-17 12:51:06	ewer	everwork.py - [<module>]	MainThread - 11912 - 14812	DEBUG: 程序启动……
2018-01-17 12:51:06	ewer	everwork.py - [<module>]	MainThread - 11912 - 14812	DEBUG: 配置文件读取成功
2018-01-17 12:51:06	ewer	everfunc.py - [wrapper]	MainThread - 11912 - 14812	DEBUG: get_notestore 启动运行
2018-01-17 12:51:07	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11912 - 14812	DEBUG: 动用了Evernote API 0 次……
2018-01-17 12:51:07	ewer	everfunc.py - [get_notestore]	MainThread - 11912 - 14812	DEBUG: 成功连接Evernote服务器！
2018-01-17 12:51:11	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11912 - 14812	DEBUG: 动用了Evernote API 1 次……
2018-01-17 12:51:11	ewer	everfunc.py - [imglist2note]	MainThread - 11912 - 14812	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 12:51:12	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11912 - 14812	DEBUG: 动用了Evernote API 2 次……
2018-01-17 12:51:16	ewer	everfunc.py - [writeini]	MainThread - 11912 - 14812	INFO: Evernote API调用次数：3，写入配置文件data\everwork.ini
2018-01-17 12:51:16	ewer	everwork.py - [<module>]	MainThread - 11912 - 14812	DEBUG: 程序结束！
2018-01-17 12:51:56	ewer	everwork.py - [<module>]	MainThread - 13740 - 3644	DEBUG: 程序启动……
2018-01-17 12:51:56	ewer	everwork.py - [<module>]	MainThread - 13740 - 3644	DEBUG: 配置文件读取成功
2018-01-17 12:51:56	ewer	everfunc.py - [wrapper]	MainThread - 13740 - 3644	DEBUG: get_notestore 启动运行
2018-01-17 12:51:57	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13740 - 3644	DEBUG: 动用了Evernote API 3 次……
2018-01-17 12:51:57	ewer	everfunc.py - [get_notestore]	MainThread - 13740 - 3644	DEBUG: 成功连接Evernote服务器！
2018-01-17 12:52:00	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13740 - 3644	DEBUG: 动用了Evernote API 4 次……
2018-01-17 12:52:00	ewer	everfunc.py - [imglist2note]	MainThread - 13740 - 3644	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 12:52:01	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13740 - 3644	DEBUG: 动用了Evernote API 5 次……
2018-01-17 12:52:01	ewer	everfunc.py - [writeini]	MainThread - 13740 - 3644	INFO: Evernote API调用次数：6，写入配置文件data\everwork.ini
2018-01-17 12:52:01	ewer	everwork.py - [<module>]	MainThread - 13740 - 3644	DEBUG: 程序结束！
2018-01-17 12:53:09	ewer	everwork.py - [<module>]	MainThread - 12400 - 6284	DEBUG: 程序启动……
2018-01-17 12:53:09	ewer	everwork.py - [<module>]	MainThread - 12400 - 6284	DEBUG: 配置文件读取成功
2018-01-17 12:53:09	ewer	everfunc.py - [wrapper]	MainThread - 12400 - 6284	DEBUG: get_notestore 启动运行
2018-01-17 12:53:10	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12400 - 6284	DEBUG: 动用了Evernote API 6 次……
2018-01-17 12:53:10	ewer	everfunc.py - [get_notestore]	MainThread - 12400 - 6284	DEBUG: 成功连接Evernote服务器！
2018-01-17 12:53:13	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12400 - 6284	DEBUG: 动用了Evernote API 7 次……
2018-01-17 12:53:13	ewer	everfunc.py - [imglist2note]	MainThread - 12400 - 6284	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 12:53:14	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12400 - 6284	DEBUG: 动用了Evernote API 8 次……
2018-01-17 12:53:14	ewer	everfunc.py - [writeini]	MainThread - 12400 - 6284	INFO: Evernote API调用次数：9，写入配置文件data\everwork.ini
2018-01-17 12:53:14	ewer	everwork.py - [<module>]	MainThread - 12400 - 6284	DEBUG: 程序结束！
2018-01-17 12:54:47	ewer	everwork.py - [<module>]	MainThread - 14136 - 14448	DEBUG: 程序启动……
2018-01-17 12:54:47	ewer	everwork.py - [<module>]	MainThread - 14136 - 14448	DEBUG: 配置文件读取成功
2018-01-17 12:54:47	ewer	everfunc.py - [wrapper]	MainThread - 14136 - 14448	DEBUG: get_notestore 启动运行
2018-01-17 12:54:48	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14136 - 14448	DEBUG: 动用了Evernote API 9 次……
2018-01-17 12:54:48	ewer	everfunc.py - [get_notestore]	MainThread - 14136 - 14448	DEBUG: 成功连接Evernote服务器！
2018-01-17 12:54:51	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14136 - 14448	DEBUG: 动用了Evernote API 10 次……
2018-01-17 12:54:51	ewer	everfunc.py - [imglist2note]	MainThread - 14136 - 14448	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 12:54:52	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14136 - 14448	DEBUG: 动用了Evernote API 11 次……
2018-01-17 12:54:52	ewer	everfunc.py - [writeini]	MainThread - 14136 - 14448	INFO: Evernote API调用次数：12，写入配置文件data\everwork.ini
2018-01-17 12:54:52	ewer	everwork.py - [<module>]	MainThread - 14136 - 14448	DEBUG: 程序结束！
2018-01-17 12:56:22	ewer	everwork.py - [<module>]	MainThread - 3788 - 12776	DEBUG: 程序启动……
2018-01-17 12:56:22	ewer	everwork.py - [<module>]	MainThread - 3788 - 12776	DEBUG: 配置文件读取成功
2018-01-17 12:56:22	ewer	everfunc.py - [wrapper]	MainThread - 3788 - 12776	DEBUG: get_notestore 启动运行
2018-01-17 12:56:23	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3788 - 12776	DEBUG: 动用了Evernote API 12 次……
2018-01-17 12:56:23	ewer	everfunc.py - [get_notestore]	MainThread - 3788 - 12776	DEBUG: 成功连接Evernote服务器！
2018-01-17 12:56:26	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3788 - 12776	DEBUG: 动用了Evernote API 13 次……
2018-01-17 12:56:26	ewer	everfunc.py - [imglist2note]	MainThread - 3788 - 12776	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 12:56:27	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3788 - 12776	DEBUG: 动用了Evernote API 14 次……
2018-01-17 12:57:12	ewer	everfunc.py - [<module>]	MainThread - 13692 - 7512	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 12:56:27,14]
2018-01-17 12:57:12	ewer	everwork.py - [<module>]	MainThread - 13692 - 7512	DEBUG: 程序启动……
2018-01-17 12:57:12	ewer	everwork.py - [<module>]	MainThread - 13692 - 7512	DEBUG: 配置文件读取成功
2018-01-17 12:57:12	ewer	everfunc.py - [wrapper]	MainThread - 13692 - 7512	DEBUG: get_notestore 启动运行
2018-01-17 12:57:14	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13692 - 7512	DEBUG: 动用了Evernote API 15 次……
2018-01-17 12:57:14	ewer	everfunc.py - [get_notestore]	MainThread - 13692 - 7512	DEBUG: 成功连接Evernote服务器！
2018-01-17 12:57:17	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13692 - 7512	DEBUG: 动用了Evernote API 16 次……
2018-01-17 12:57:17	ewer	everfunc.py - [imglist2note]	MainThread - 13692 - 7512	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 12:57:17	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13692 - 7512	DEBUG: 动用了Evernote API 17 次……
2018-01-17 12:57:17	ewer	everfunc.py - [writeini]	MainThread - 13692 - 7512	INFO: Evernote API调用次数：18，写入配置文件data\everwork.ini
2018-01-17 12:57:17	ewer	everwork.py - [<module>]	MainThread - 13692 - 7512	DEBUG: 程序结束！
2018-01-17 12:58:17	ewer	everwork.py - [<module>]	MainThread - 4884 - 13416	DEBUG: 程序启动……
2018-01-17 12:58:17	ewer	everwork.py - [<module>]	MainThread - 4884 - 13416	DEBUG: 配置文件读取成功
2018-01-17 12:58:17	ewer	everfunc.py - [wrapper]	MainThread - 4884 - 13416	DEBUG: get_notestore 启动运行
2018-01-17 12:58:18	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 4884 - 13416	DEBUG: 动用了Evernote API 18 次……
2018-01-17 12:58:18	ewer	everfunc.py - [get_notestore]	MainThread - 4884 - 13416	DEBUG: 成功连接Evernote服务器！
2018-01-17 12:58:21	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 4884 - 13416	DEBUG: 动用了Evernote API 19 次……
2018-01-17 12:58:21	ewer	everfunc.py - [imglist2note]	MainThread - 4884 - 13416	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 12:58:22	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 4884 - 13416	DEBUG: 动用了Evernote API 20 次……
2018-01-17 12:58:22	ewer	everfunc.py - [writeini]	MainThread - 4884 - 13416	INFO: Evernote API调用次数：21，写入配置文件data\everwork.ini
2018-01-17 12:58:22	ewer	everwork.py - [<module>]	MainThread - 4884 - 13416	DEBUG: 程序结束！
2018-01-17 12:59:51	ewer	everwork.py - [<module>]	MainThread - 14864 - 5932	DEBUG: 程序启动……
2018-01-17 12:59:51	ewer	everwork.py - [<module>]	MainThread - 14864 - 5932	DEBUG: 配置文件读取成功
2018-01-17 12:59:51	ewer	everfunc.py - [wrapper]	MainThread - 14864 - 5932	DEBUG: get_notestore 启动运行
2018-01-17 12:59:53	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14864 - 5932	DEBUG: 动用了Evernote API 21 次……
2018-01-17 12:59:53	ewer	everfunc.py - [get_notestore]	MainThread - 14864 - 5932	DEBUG: 成功连接Evernote服务器！
2018-01-17 12:59:56	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14864 - 5932	DEBUG: 动用了Evernote API 22 次……
2018-01-17 12:59:56	ewer	everfunc.py - [imglist2note]	MainThread - 14864 - 5932	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 12:59:57	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14864 - 5932	DEBUG: 动用了Evernote API 23 次……
2018-01-17 12:59:57	ewer	everfunc.py - [writeini]	MainThread - 14864 - 5932	INFO: Evernote API调用次数：24，写入配置文件data\everwork.ini
2018-01-17 12:59:57	ewer	everwork.py - [<module>]	MainThread - 14864 - 5932	DEBUG: 程序结束！
2018-01-17 13:01:51	ewer	everfunc.py - [writeini]	MainThread - 15336 - 14388	INFO: Evernote API调用次数：0，写入配置文件data\everwork.ini
2018-01-17 13:01:51	ewer	everwork.py - [<module>]	MainThread - 15336 - 14388	DEBUG: 程序启动……
2018-01-17 13:01:51	ewer	everwork.py - [<module>]	MainThread - 15336 - 14388	DEBUG: 配置文件读取成功
2018-01-17 13:01:51	ewer	everfunc.py - [wrapper]	MainThread - 15336 - 14388	DEBUG: get_notestore 启动运行
2018-01-17 13:01:52	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15336 - 14388	DEBUG: 动用了Evernote API 0 次……
2018-01-17 13:01:52	ewer	everfunc.py - [get_notestore]	MainThread - 15336 - 14388	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:01:55	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15336 - 14388	DEBUG: 动用了Evernote API 1 次……
2018-01-17 13:01:55	ewer	everfunc.py - [imglist2note]	MainThread - 15336 - 14388	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 13:01:56	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15336 - 14388	DEBUG: 动用了Evernote API 2 次……
2018-01-17 13:01:56	ewer	everfunc.py - [writeini]	MainThread - 15336 - 14388	INFO: Evernote API调用次数：3，写入配置文件data\everwork.ini
2018-01-17 13:01:56	ewer	everwork.py - [<module>]	MainThread - 15336 - 14388	DEBUG: 程序结束！
2018-01-17 13:02:49	ewer	everwork.py - [<module>]	MainThread - 8460 - 3760	DEBUG: 程序启动……
2018-01-17 13:02:49	ewer	everwork.py - [<module>]	MainThread - 8460 - 3760	DEBUG: 配置文件读取成功
2018-01-17 13:02:49	ewer	everfunc.py - [wrapper]	MainThread - 8460 - 3760	DEBUG: get_notestore 启动运行
2018-01-17 13:02:51	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8460 - 3760	DEBUG: 动用了Evernote API 3 次……
2018-01-17 13:02:51	ewer	everfunc.py - [get_notestore]	MainThread - 8460 - 3760	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:02:54	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8460 - 3760	DEBUG: 动用了Evernote API 4 次……
2018-01-17 13:02:54	ewer	everfunc.py - [imglist2note]	MainThread - 8460 - 3760	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 13:02:54	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8460 - 3760	DEBUG: 动用了Evernote API 5 次……
2018-01-17 13:02:55	ewer	everfunc.py - [writeini]	MainThread - 8460 - 3760	INFO: Evernote API调用次数：6，写入配置文件data\everwork.ini
2018-01-17 13:02:55	ewer	everwork.py - [<module>]	MainThread - 8460 - 3760	DEBUG: 程序结束！
2018-01-17 13:03:36	ewer	everwork.py - [<module>]	MainThread - 1500 - 10664	DEBUG: 程序启动……
2018-01-17 13:03:36	ewer	everwork.py - [<module>]	MainThread - 1500 - 10664	DEBUG: 配置文件读取成功
2018-01-17 13:03:36	ewer	everfunc.py - [wrapper]	MainThread - 1500 - 10664	DEBUG: get_notestore 启动运行
2018-01-17 13:03:37	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1500 - 10664	DEBUG: 动用了Evernote API 6 次……
2018-01-17 13:03:37	ewer	everfunc.py - [get_notestore]	MainThread - 1500 - 10664	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:03:40	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1500 - 10664	DEBUG: 动用了Evernote API 7 次……
2018-01-17 13:03:40	ewer	everfunc.py - [imglist2note]	MainThread - 1500 - 10664	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 13:03:41	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1500 - 10664	DEBUG: 动用了Evernote API 8 次……
2018-01-17 13:03:41	ewer	everfunc.py - [writeini]	MainThread - 1500 - 10664	INFO: Evernote API调用次数：9，写入配置文件data\everwork.ini
2018-01-17 13:03:41	ewer	everwork.py - [<module>]	MainThread - 1500 - 10664	DEBUG: 程序结束！
2018-01-17 13:04:02	ewer	everwork.py - [<module>]	MainThread - 1864 - 14072	DEBUG: 程序启动……
2018-01-17 13:04:02	ewer	everwork.py - [<module>]	MainThread - 1864 - 14072	DEBUG: 配置文件读取成功
2018-01-17 13:04:02	ewer	everfunc.py - [wrapper]	MainThread - 1864 - 14072	DEBUG: get_notestore 启动运行
2018-01-17 13:04:04	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1864 - 14072	DEBUG: 动用了Evernote API 9 次……
2018-01-17 13:04:04	ewer	everfunc.py - [get_notestore]	MainThread - 1864 - 14072	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:04:07	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1864 - 14072	DEBUG: 动用了Evernote API 10 次……
2018-01-17 13:04:07	ewer	everfunc.py - [imglist2note]	MainThread - 1864 - 14072	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 13:04:07	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1864 - 14072	DEBUG: 动用了Evernote API 11 次……
2018-01-17 13:04:08	ewer	everfunc.py - [writeini]	MainThread - 1864 - 14072	INFO: Evernote API调用次数：12，写入配置文件data\everwork.ini
2018-01-17 13:04:08	ewer	everwork.py - [<module>]	MainThread - 1864 - 14072	DEBUG: 程序结束！
2018-01-17 13:04:56	ewer	everwork.py - [<module>]	MainThread - 13584 - 3732	DEBUG: 程序启动……
2018-01-17 13:04:56	ewer	everwork.py - [<module>]	MainThread - 13584 - 3732	DEBUG: 配置文件读取成功
2018-01-17 13:04:56	ewer	everfunc.py - [wrapper]	MainThread - 13584 - 3732	DEBUG: get_notestore 启动运行
2018-01-17 13:04:58	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13584 - 3732	DEBUG: 动用了Evernote API 12 次……
2018-01-17 13:04:58	ewer	everfunc.py - [get_notestore]	MainThread - 13584 - 3732	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:05:01	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13584 - 3732	DEBUG: 动用了Evernote API 13 次……
2018-01-17 13:05:01	ewer	everfunc.py - [imglist2note]	MainThread - 13584 - 3732	INFO: 成功更新了笔记《武汉天气图》，guid：296f57a3-c660-4dd5-885a-56492deb2cee。
2018-01-17 13:05:01	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13584 - 3732	DEBUG: 动用了Evernote API 14 次……
2018-01-17 13:05:01	ewer	everfunc.py - [writeini]	MainThread - 13584 - 3732	INFO: Evernote API调用次数：15，写入配置文件data\everwork.ini
2018-01-17 13:05:01	ewer	everwork.py - [<module>]	MainThread - 13584 - 3732	DEBUG: 程序结束！
2018-01-17 13:27:01	ewer	everwork.py - [<module>]	MainThread - 6568 - 1680	DEBUG: 程序启动……
2018-01-17 13:27:01	ewer	everwork.py - [<module>]	MainThread - 6568 - 1680	DEBUG: 配置文件读取成功
2018-01-17 13:27:01	ewer	everfunc.py - [wrapper]	MainThread - 6568 - 1680	DEBUG: get_notestore 启动运行
2018-01-17 13:27:02	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 6568 - 1680	DEBUG: 动用了Evernote API 15 次……
2018-01-17 13:27:02	ewer	everfunc.py - [get_notestore]	MainThread - 6568 - 1680	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:27:03	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 6568 - 1680	DEBUG: 动用了Evernote API 16 次……
2018-01-17 13:27:03	ewer	everfunc.py - [writeini]	MainThread - 6568 - 1680	INFO: Evernote API调用次数：17，写入配置文件data\everwork.ini
2018-01-17 13:27:03	ewer	everwork.py - [<module>]	MainThread - 6568 - 1680	DEBUG: 程序结束！
2018-01-17 13:28:22	ewer	everwork.py - [<module>]	MainThread - 12384 - 14928	DEBUG: 程序启动……
2018-01-17 13:28:22	ewer	everwork.py - [<module>]	MainThread - 12384 - 14928	DEBUG: 配置文件读取成功
2018-01-17 13:28:22	ewer	everfunc.py - [wrapper]	MainThread - 12384 - 14928	DEBUG: get_notestore 启动运行
2018-01-17 13:28:23	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12384 - 14928	DEBUG: 动用了Evernote API 17 次……
2018-01-17 13:28:23	ewer	everfunc.py - [get_notestore]	MainThread - 12384 - 14928	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:28:24	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12384 - 14928	DEBUG: 动用了Evernote API 18 次……
2018-01-17 13:28:24	ewer	everfunc.py - [writeini]	MainThread - 12384 - 14928	INFO: Evernote API调用次数：19，写入配置文件data\everwork.ini
2018-01-17 13:28:24	ewer	everwork.py - [<module>]	MainThread - 12384 - 14928	DEBUG: 程序结束！
2018-01-17 13:32:27	ewer	everwork.py - [<module>]	MainThread - 7348 - 4864	DEBUG: 程序启动……
2018-01-17 13:32:27	ewer	everwork.py - [<module>]	MainThread - 7348 - 4864	DEBUG: 配置文件读取成功
2018-01-17 13:32:27	ewer	everfunc.py - [wrapper]	MainThread - 7348 - 4864	DEBUG: get_notestore 启动运行
2018-01-17 13:32:29	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 7348 - 4864	DEBUG: 动用了Evernote API 19 次……
2018-01-17 13:32:29	ewer	everfunc.py - [get_notestore]	MainThread - 7348 - 4864	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:32:30	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 7348 - 4864	DEBUG: 动用了Evernote API 20 次……
2018-01-17 13:32:30	ewer	everfunc.py - [writeini]	MainThread - 7348 - 4864	INFO: Evernote API调用次数：21，写入配置文件data\everwork.ini
2018-01-17 13:32:30	ewer	everwork.py - [<module>]	MainThread - 7348 - 4864	DEBUG: 程序结束！
2018-01-17 13:34:26	ewer	everwork.py - [<module>]	MainThread - 2368 - 12124	DEBUG: 程序启动……
2018-01-17 13:34:26	ewer	everwork.py - [<module>]	MainThread - 2368 - 12124	DEBUG: 配置文件读取成功
2018-01-17 13:34:26	ewer	everfunc.py - [wrapper]	MainThread - 2368 - 12124	DEBUG: get_notestore 启动运行
2018-01-17 13:34:27	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2368 - 12124	DEBUG: 动用了Evernote API 21 次……
2018-01-17 13:34:27	ewer	everfunc.py - [get_notestore]	MainThread - 2368 - 12124	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:34:28	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2368 - 12124	DEBUG: 动用了Evernote API 22 次……
2018-01-17 13:34:28	ewer	everfunc.py - [writeini]	MainThread - 2368 - 12124	INFO: Evernote API调用次数：23，写入配置文件data\everwork.ini
2018-01-17 13:34:28	ewer	everwork.py - [<module>]	MainThread - 2368 - 12124	DEBUG: 程序结束！
2018-01-17 13:35:10	ewer	everwork.py - [<module>]	MainThread - 10040 - 4516	DEBUG: 程序启动……
2018-01-17 13:35:10	ewer	everwork.py - [<module>]	MainThread - 10040 - 4516	DEBUG: 配置文件读取成功
2018-01-17 13:35:10	ewer	everfunc.py - [wrapper]	MainThread - 10040 - 4516	DEBUG: get_notestore 启动运行
2018-01-17 13:35:11	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10040 - 4516	DEBUG: 动用了Evernote API 23 次……
2018-01-17 13:35:11	ewer	everfunc.py - [get_notestore]	MainThread - 10040 - 4516	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:35:12	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10040 - 4516	DEBUG: 动用了Evernote API 24 次……
2018-01-17 13:35:12	ewer	everfunc.py - [writeini]	MainThread - 10040 - 4516	INFO: Evernote API调用次数：25，写入配置文件data\everwork.ini
2018-01-17 13:35:12	ewer	everwork.py - [<module>]	MainThread - 10040 - 4516	DEBUG: 程序结束！
2018-01-17 13:36:15	ewer	everwork.py - [<module>]	MainThread - 8020 - 12624	DEBUG: 程序启动……
2018-01-17 13:36:15	ewer	everwork.py - [<module>]	MainThread - 8020 - 12624	DEBUG: 配置文件读取成功
2018-01-17 13:36:15	ewer	everfunc.py - [wrapper]	MainThread - 8020 - 12624	DEBUG: get_notestore 启动运行
2018-01-17 13:36:17	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8020 - 12624	DEBUG: 动用了Evernote API 25 次……
2018-01-17 13:36:17	ewer	everfunc.py - [get_notestore]	MainThread - 8020 - 12624	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:36:18	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8020 - 12624	DEBUG: 动用了Evernote API 26 次……
2018-01-17 13:36:18	ewer	everfunc.py - [writeini]	MainThread - 8020 - 12624	INFO: Evernote API调用次数：27，写入配置文件data\everwork.ini
2018-01-17 13:36:18	ewer	everwork.py - [<module>]	MainThread - 8020 - 12624	DEBUG: 程序结束！
2018-01-17 13:58:43	ewer	everwork.py - [<module>]	MainThread - 10228 - 1292	DEBUG: 程序启动……
2018-01-17 13:58:43	ewer	everwork.py - [<module>]	MainThread - 10228 - 1292	DEBUG: 配置文件读取成功
2018-01-17 13:58:43	ewer	everfunc.py - [wrapper]	MainThread - 10228 - 1292	DEBUG: get_notestore 启动运行
2018-01-17 13:58:45	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10228 - 1292	DEBUG: 动用了Evernote API 27 次……
2018-01-17 13:58:45	ewer	everfunc.py - [get_notestore]	MainThread - 10228 - 1292	DEBUG: 成功连接Evernote服务器！
2018-01-17 13:58:46	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10228 - 1292	DEBUG: 动用了Evernote API 28 次……
2018-01-17 13:58:46	ewer	everfunc.py - [writeini]	MainThread - 10228 - 1292	INFO: Evernote API调用次数：29，写入配置文件data\everwork.ini
2018-01-17 13:58:46	ewer	everwork.py - [<module>]	MainThread - 10228 - 1292	DEBUG: 程序结束！
2018-01-17 14:05:10	ewer	everfunc.py - [writeini]	MainThread - 3924 - 3876	INFO: Evernote API调用次数：0，写入配置文件data\everwork.ini
2018-01-17 14:05:10	ewer	everwork.py - [<module>]	MainThread - 3924 - 3876	DEBUG: 程序启动……
2018-01-17 14:05:10	ewer	everwork.py - [<module>]	MainThread - 3924 - 3876	DEBUG: 配置文件读取成功
2018-01-17 14:05:10	ewer	everfunc.py - [wrapper]	MainThread - 3924 - 3876	DEBUG: get_notestore 启动运行
2018-01-17 14:05:12	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3924 - 3876	DEBUG: 动用了Evernote API 0 次……
2018-01-17 14:05:12	ewer	everfunc.py - [get_notestore]	MainThread - 3924 - 3876	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:05:12	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3924 - 3876	DEBUG: 动用了Evernote API 1 次……
2018-01-17 14:05:12	ewer	everfunc.py - [writeini]	MainThread - 3924 - 3876	INFO: Evernote API调用次数：2，写入配置文件data\everwork.ini
2018-01-17 14:05:12	ewer	everwork.py - [<module>]	MainThread - 3924 - 3876	DEBUG: 程序结束！
2018-01-17 14:05:33	ewer	everwork.py - [<module>]	MainThread - 592 - 12272	DEBUG: 程序启动……
2018-01-17 14:05:33	ewer	everwork.py - [<module>]	MainThread - 592 - 12272	DEBUG: 配置文件读取成功
2018-01-17 14:05:33	ewer	everfunc.py - [wrapper]	MainThread - 592 - 12272	DEBUG: get_notestore 启动运行
2018-01-17 14:05:34	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 592 - 12272	DEBUG: 动用了Evernote API 2 次……
2018-01-17 14:05:34	ewer	everfunc.py - [get_notestore]	MainThread - 592 - 12272	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:05:35	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 592 - 12272	DEBUG: 动用了Evernote API 3 次……
2018-01-17 14:05:35	ewer	everfunc.py - [writeini]	MainThread - 592 - 12272	INFO: Evernote API调用次数：4，写入配置文件data\everwork.ini
2018-01-17 14:05:35	ewer	everwork.py - [<module>]	MainThread - 592 - 12272	DEBUG: 程序结束！
2018-01-17 14:06:21	ewer	everwork.py - [<module>]	MainThread - 11956 - 3264	DEBUG: 程序启动……
2018-01-17 14:06:21	ewer	everwork.py - [<module>]	MainThread - 11956 - 3264	DEBUG: 配置文件读取成功
2018-01-17 14:06:21	ewer	everfunc.py - [wrapper]	MainThread - 11956 - 3264	DEBUG: get_notestore 启动运行
2018-01-17 14:06:23	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11956 - 3264	DEBUG: 动用了Evernote API 4 次……
2018-01-17 14:06:23	ewer	everfunc.py - [get_notestore]	MainThread - 11956 - 3264	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:06:24	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11956 - 3264	DEBUG: 动用了Evernote API 5 次……
2018-01-17 14:06:24	ewer	everfunc.py - [writeini]	MainThread - 11956 - 3264	INFO: Evernote API调用次数：6，写入配置文件data\everwork.ini
2018-01-17 14:06:24	ewer	everwork.py - [<module>]	MainThread - 11956 - 3264	DEBUG: 程序结束！
2018-01-17 14:18:10	ewer	everwork.py - [<module>]	MainThread - 5240 - 8796	DEBUG: 程序启动……
2018-01-17 14:18:10	ewer	everwork.py - [<module>]	MainThread - 5240 - 8796	DEBUG: 配置文件读取成功
2018-01-17 14:18:10	ewer	everfunc.py - [wrapper]	MainThread - 5240 - 8796	DEBUG: get_notestore 启动运行
2018-01-17 14:18:11	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5240 - 8796	DEBUG: 动用了Evernote API 6 次……
2018-01-17 14:18:11	ewer	everfunc.py - [get_notestore]	MainThread - 5240 - 8796	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:18:12	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5240 - 8796	DEBUG: 动用了Evernote API 7 次……
2018-01-17 14:18:12	ewer	everfunc.py - [writeini]	MainThread - 5240 - 8796	INFO: Evernote API调用次数：8，写入配置文件data\everwork.ini
2018-01-17 14:18:12	ewer	everwork.py - [<module>]	MainThread - 5240 - 8796	DEBUG: 程序结束！
2018-01-17 14:19:29	ewer	everwork.py - [<module>]	MainThread - 424 - 6812	DEBUG: 程序启动……
2018-01-17 14:19:29	ewer	everwork.py - [<module>]	MainThread - 424 - 6812	DEBUG: 配置文件读取成功
2018-01-17 14:19:29	ewer	everfunc.py - [wrapper]	MainThread - 424 - 6812	DEBUG: get_notestore 启动运行
2018-01-17 14:19:31	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 424 - 6812	DEBUG: 动用了Evernote API 8 次……
2018-01-17 14:19:31	ewer	everfunc.py - [get_notestore]	MainThread - 424 - 6812	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:19:31	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 424 - 6812	DEBUG: 动用了Evernote API 9 次……
2018-01-17 14:19:31	ewer	everfunc.py - [writeini]	MainThread - 424 - 6812	INFO: Evernote API调用次数：10，写入配置文件data\everwork.ini
2018-01-17 14:19:31	ewer	everwork.py - [<module>]	MainThread - 424 - 6812	DEBUG: 程序结束！
2018-01-17 14:19:48	ewer	everwork.py - [<module>]	MainThread - 2836 - 13592	DEBUG: 程序启动……
2018-01-17 14:19:48	ewer	everwork.py - [<module>]	MainThread - 2836 - 13592	DEBUG: 配置文件读取成功
2018-01-17 14:19:48	ewer	everfunc.py - [wrapper]	MainThread - 2836 - 13592	DEBUG: get_notestore 启动运行
2018-01-17 14:19:50	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2836 - 13592	DEBUG: 动用了Evernote API 10 次……
2018-01-17 14:19:50	ewer	everfunc.py - [get_notestore]	MainThread - 2836 - 13592	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:19:51	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2836 - 13592	DEBUG: 动用了Evernote API 11 次……
2018-01-17 14:19:51	ewer	everfunc.py - [writeini]	MainThread - 2836 - 13592	INFO: Evernote API调用次数：12，写入配置文件data\everwork.ini
2018-01-17 14:19:51	ewer	everwork.py - [<module>]	MainThread - 2836 - 13592	DEBUG: 程序结束！
2018-01-17 14:21:19	ewer	everwork.py - [<module>]	MainThread - 10560 - 12052	DEBUG: 程序启动……
2018-01-17 14:21:19	ewer	everwork.py - [<module>]	MainThread - 10560 - 12052	DEBUG: 配置文件读取成功
2018-01-17 14:21:19	ewer	everfunc.py - [wrapper]	MainThread - 10560 - 12052	DEBUG: get_notestore 启动运行
2018-01-17 14:21:21	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10560 - 12052	DEBUG: 动用了Evernote API 12 次……
2018-01-17 14:21:21	ewer	everfunc.py - [get_notestore]	MainThread - 10560 - 12052	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:21:22	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10560 - 12052	DEBUG: 动用了Evernote API 13 次……
2018-01-17 14:22:49	ewer	everfunc.py - [<module>]	MainThread - 8112 - 12264	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:21:22,13]
2018-01-17 14:22:49	ewer	everwork.py - [<module>]	MainThread - 8112 - 12264	DEBUG: 程序启动……
2018-01-17 14:22:49	ewer	everwork.py - [<module>]	MainThread - 8112 - 12264	DEBUG: 配置文件读取成功
2018-01-17 14:22:49	ewer	everfunc.py - [wrapper]	MainThread - 8112 - 12264	DEBUG: get_notestore 启动运行
2018-01-17 14:22:50	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8112 - 12264	DEBUG: 动用了Evernote API 14 次……
2018-01-17 14:22:50	ewer	everfunc.py - [get_notestore]	MainThread - 8112 - 12264	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:22:51	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8112 - 12264	DEBUG: 动用了Evernote API 15 次……
2018-01-17 14:22:51	ewer	everfunc.py - [writeini]	MainThread - 8112 - 12264	INFO: Evernote API调用次数：16，写入配置文件data\everwork.ini
2018-01-17 14:22:51	ewer	everwork.py - [<module>]	MainThread - 8112 - 12264	DEBUG: 程序结束！
2018-01-17 14:23:12	ewer	everwork.py - [<module>]	MainThread - 13788 - 11756	DEBUG: 程序启动……
2018-01-17 14:23:12	ewer	everwork.py - [<module>]	MainThread - 13788 - 11756	DEBUG: 配置文件读取成功
2018-01-17 14:23:12	ewer	everfunc.py - [wrapper]	MainThread - 13788 - 11756	DEBUG: get_notestore 启动运行
2018-01-17 14:23:14	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13788 - 11756	DEBUG: 动用了Evernote API 16 次……
2018-01-17 14:23:14	ewer	everfunc.py - [get_notestore]	MainThread - 13788 - 11756	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:23:15	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13788 - 11756	DEBUG: 动用了Evernote API 17 次……
2018-01-17 14:23:15	ewer	everfunc.py - [writeini]	MainThread - 13788 - 11756	INFO: Evernote API调用次数：18，写入配置文件data\everwork.ini
2018-01-17 14:23:15	ewer	everwork.py - [<module>]	MainThread - 13788 - 11756	DEBUG: 程序结束！
2018-01-17 14:23:37	ewer	everwork.py - [<module>]	MainThread - 3224 - 12280	DEBUG: 程序启动……
2018-01-17 14:23:37	ewer	everwork.py - [<module>]	MainThread - 3224 - 12280	DEBUG: 配置文件读取成功
2018-01-17 14:23:37	ewer	everfunc.py - [wrapper]	MainThread - 3224 - 12280	DEBUG: get_notestore 启动运行
2018-01-17 14:23:39	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3224 - 12280	DEBUG: 动用了Evernote API 18 次……
2018-01-17 14:23:39	ewer	everfunc.py - [get_notestore]	MainThread - 3224 - 12280	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:23:40	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3224 - 12280	DEBUG: 动用了Evernote API 19 次……
2018-01-17 14:23:40	ewer	everfunc.py - [writeini]	MainThread - 3224 - 12280	INFO: Evernote API调用次数：20，写入配置文件data\everwork.ini
2018-01-17 14:23:40	ewer	everwork.py - [<module>]	MainThread - 3224 - 12280	DEBUG: 程序结束！
2018-01-17 14:26:23	ewer	everwork.py - [<module>]	MainThread - 1080 - 14664	DEBUG: 程序启动……
2018-01-17 14:26:23	ewer	everwork.py - [<module>]	MainThread - 1080 - 14664	DEBUG: 配置文件读取成功
2018-01-17 14:26:23	ewer	everfunc.py - [wrapper]	MainThread - 1080 - 14664	DEBUG: get_notestore 启动运行
2018-01-17 14:26:25	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1080 - 14664	DEBUG: 动用了Evernote API 20 次……
2018-01-17 14:26:25	ewer	everfunc.py - [get_notestore]	MainThread - 1080 - 14664	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:26:26	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1080 - 14664	DEBUG: 动用了Evernote API 21 次……
2018-01-17 14:26:26	ewer	everfunc.py - [writeini]	MainThread - 1080 - 14664	INFO: Evernote API调用次数：22，写入配置文件data\everwork.ini
2018-01-17 14:26:26	ewer	everwork.py - [<module>]	MainThread - 1080 - 14664	DEBUG: 程序结束！
2018-01-17 14:30:38	ewer	everwork.py - [<module>]	MainThread - 13052 - 11456	DEBUG: 程序启动……
2018-01-17 14:30:38	ewer	everwork.py - [<module>]	MainThread - 13052 - 11456	DEBUG: 配置文件读取成功
2018-01-17 14:30:38	ewer	everfunc.py - [wrapper]	MainThread - 13052 - 11456	DEBUG: get_notestore 启动运行
2018-01-17 14:30:39	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13052 - 11456	DEBUG: 动用了Evernote API 22 次……
2018-01-17 14:30:39	ewer	everfunc.py - [get_notestore]	MainThread - 13052 - 11456	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:30:40	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13052 - 11456	DEBUG: 动用了Evernote API 23 次……
2018-01-17 14:30:40	ewer	everfunc.py - [writeini]	MainThread - 13052 - 11456	INFO: Evernote API调用次数：24，写入配置文件data\everwork.ini
2018-01-17 14:30:40	ewer	everwork.py - [<module>]	MainThread - 13052 - 11456	DEBUG: 程序结束！
2018-01-17 14:31:05	ewer	everwork.py - [<module>]	MainThread - 8004 - 13284	DEBUG: 程序启动……
2018-01-17 14:31:05	ewer	everwork.py - [<module>]	MainThread - 8004 - 13284	DEBUG: 配置文件读取成功
2018-01-17 14:31:05	ewer	everfunc.py - [wrapper]	MainThread - 8004 - 13284	DEBUG: get_notestore 启动运行
2018-01-17 14:31:06	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8004 - 13284	DEBUG: 动用了Evernote API 24 次……
2018-01-17 14:31:06	ewer	everfunc.py - [get_notestore]	MainThread - 8004 - 13284	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:31:07	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8004 - 13284	DEBUG: 动用了Evernote API 25 次……
2018-01-17 14:31:18	ewer	everfunc.py - [<module>]	MainThread - 13308 - 5668	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:31:07,25]
2018-01-17 14:31:18	ewer	everwork.py - [<module>]	MainThread - 13308 - 5668	DEBUG: 程序启动……
2018-01-17 14:31:18	ewer	everwork.py - [<module>]	MainThread - 13308 - 5668	DEBUG: 配置文件读取成功
2018-01-17 14:31:18	ewer	everfunc.py - [wrapper]	MainThread - 13308 - 5668	DEBUG: get_notestore 启动运行
2018-01-17 14:31:19	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13308 - 5668	DEBUG: 动用了Evernote API 26 次……
2018-01-17 14:31:19	ewer	everfunc.py - [get_notestore]	MainThread - 13308 - 5668	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:31:20	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13308 - 5668	DEBUG: 动用了Evernote API 27 次……
2018-01-17 14:31:20	ewer	everfunc.py - [writeini]	MainThread - 13308 - 5668	INFO: Evernote API调用次数：28，写入配置文件data\everwork.ini
2018-01-17 14:31:20	ewer	everwork.py - [<module>]	MainThread - 13308 - 5668	DEBUG: 程序结束！
2018-01-17 14:33:52	ewer	everwork.py - [<module>]	MainThread - 12080 - 1444	DEBUG: 程序启动……
2018-01-17 14:33:52	ewer	everwork.py - [<module>]	MainThread - 12080 - 1444	DEBUG: 配置文件读取成功
2018-01-17 14:33:52	ewer	everfunc.py - [wrapper]	MainThread - 12080 - 1444	DEBUG: get_notestore 启动运行
2018-01-17 14:33:53	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12080 - 1444	DEBUG: 动用了Evernote API 28 次……
2018-01-17 14:33:53	ewer	everfunc.py - [get_notestore]	MainThread - 12080 - 1444	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:33:54	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12080 - 1444	DEBUG: 动用了Evernote API 29 次……
2018-01-17 14:34:56	ewer	everfunc.py - [<module>]	MainThread - 10972 - 2740	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:33:54,29]
2018-01-17 14:34:56	ewer	everwork.py - [<module>]	MainThread - 10972 - 2740	DEBUG: 程序启动……
2018-01-17 14:34:56	ewer	everwork.py - [<module>]	MainThread - 10972 - 2740	DEBUG: 配置文件读取成功
2018-01-17 14:34:56	ewer	everfunc.py - [wrapper]	MainThread - 10972 - 2740	DEBUG: get_notestore 启动运行
2018-01-17 14:34:58	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10972 - 2740	DEBUG: 动用了Evernote API 30 次……
2018-01-17 14:34:58	ewer	everfunc.py - [get_notestore]	MainThread - 10972 - 2740	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:34:59	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10972 - 2740	DEBUG: 动用了Evernote API 31 次……
2018-01-17 14:35:42	ewer	everfunc.py - [<module>]	MainThread - 4632 - 12096	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:34:59,31]
2018-01-17 14:35:42	ewer	everwork.py - [<module>]	MainThread - 4632 - 12096	DEBUG: 程序启动……
2018-01-17 14:35:42	ewer	everwork.py - [<module>]	MainThread - 4632 - 12096	DEBUG: 配置文件读取成功
2018-01-17 14:35:42	ewer	everfunc.py - [wrapper]	MainThread - 4632 - 12096	DEBUG: get_notestore 启动运行
2018-01-17 14:35:44	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 4632 - 12096	DEBUG: 动用了Evernote API 32 次……
2018-01-17 14:35:44	ewer	everfunc.py - [get_notestore]	MainThread - 4632 - 12096	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:35:45	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 4632 - 12096	DEBUG: 动用了Evernote API 33 次……
2018-01-17 14:37:24	ewer	everfunc.py - [<module>]	MainThread - 14396 - 11128	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:35:45,33]
2018-01-17 14:37:24	ewer	everwork.py - [<module>]	MainThread - 14396 - 11128	DEBUG: 程序启动……
2018-01-17 14:37:24	ewer	everwork.py - [<module>]	MainThread - 14396 - 11128	DEBUG: 配置文件读取成功
2018-01-17 14:37:24	ewer	everfunc.py - [wrapper]	MainThread - 14396 - 11128	DEBUG: get_notestore 启动运行
2018-01-17 14:37:26	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14396 - 11128	DEBUG: 动用了Evernote API 34 次……
2018-01-17 14:37:26	ewer	everfunc.py - [get_notestore]	MainThread - 14396 - 11128	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:37:26	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14396 - 11128	DEBUG: 动用了Evernote API 35 次……
2018-01-17 14:37:26	ewer	everfunc.py - [writeini]	MainThread - 14396 - 11128	INFO: Evernote API调用次数：36，写入配置文件data\everwork.ini
2018-01-17 14:37:26	ewer	everwork.py - [<module>]	MainThread - 14396 - 11128	DEBUG: 程序结束！
2018-01-17 14:38:10	ewer	everwork.py - [<module>]	MainThread - 3368 - 15100	DEBUG: 程序启动……
2018-01-17 14:38:10	ewer	everwork.py - [<module>]	MainThread - 3368 - 15100	DEBUG: 配置文件读取成功
2018-01-17 14:38:10	ewer	everfunc.py - [wrapper]	MainThread - 3368 - 15100	DEBUG: get_notestore 启动运行
2018-01-17 14:38:12	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3368 - 15100	DEBUG: 动用了Evernote API 36 次……
2018-01-17 14:38:12	ewer	everfunc.py - [get_notestore]	MainThread - 3368 - 15100	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:38:13	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3368 - 15100	DEBUG: 动用了Evernote API 37 次……
2018-01-17 14:38:13	ewer	everfunc.py - [writeini]	MainThread - 3368 - 15100	INFO: Evernote API调用次数：38，写入配置文件data\everwork.ini
2018-01-17 14:38:13	ewer	everwork.py - [<module>]	MainThread - 3368 - 15100	DEBUG: 程序结束！
2018-01-17 14:39:05	ewer	everwork.py - [<module>]	MainThread - 9628 - 11056	DEBUG: 程序启动……
2018-01-17 14:39:05	ewer	everwork.py - [<module>]	MainThread - 9628 - 11056	DEBUG: 配置文件读取成功
2018-01-17 14:39:05	ewer	everfunc.py - [wrapper]	MainThread - 9628 - 11056	DEBUG: get_notestore 启动运行
2018-01-17 14:39:06	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9628 - 11056	DEBUG: 动用了Evernote API 38 次……
2018-01-17 14:39:06	ewer	everfunc.py - [get_notestore]	MainThread - 9628 - 11056	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:39:07	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9628 - 11056	DEBUG: 动用了Evernote API 39 次……
2018-01-17 14:39:07	ewer	everfunc.py - [writeini]	MainThread - 9628 - 11056	INFO: Evernote API调用次数：40，写入配置文件data\everwork.ini
2018-01-17 14:39:07	ewer	everwork.py - [<module>]	MainThread - 9628 - 11056	DEBUG: 程序结束！
2018-01-17 14:50:23	ewer	everwork.py - [<module>]	MainThread - 12336 - 12116	DEBUG: 程序启动……
2018-01-17 14:50:23	ewer	everwork.py - [<module>]	MainThread - 12336 - 12116	DEBUG: 配置文件读取成功
2018-01-17 14:50:23	ewer	everfunc.py - [wrapper]	MainThread - 12336 - 12116	DEBUG: get_notestore 启动运行
2018-01-17 14:50:24	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12336 - 12116	DEBUG: 动用了Evernote API 40 次……
2018-01-17 14:50:24	ewer	everfunc.py - [get_notestore]	MainThread - 12336 - 12116	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:50:25	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12336 - 12116	DEBUG: 动用了Evernote API 41 次……
2018-01-17 14:51:18	ewer	everfunc.py - [<module>]	MainThread - 3104 - 10764	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:50:25,41]
2018-01-17 14:51:18	ewer	everwork.py - [<module>]	MainThread - 3104 - 10764	DEBUG: 程序启动……
2018-01-17 14:51:18	ewer	everwork.py - [<module>]	MainThread - 3104 - 10764	DEBUG: 配置文件读取成功
2018-01-17 14:51:18	ewer	everfunc.py - [wrapper]	MainThread - 3104 - 10764	DEBUG: get_notestore 启动运行
2018-01-17 14:51:20	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3104 - 10764	DEBUG: 动用了Evernote API 42 次……
2018-01-17 14:51:20	ewer	everfunc.py - [get_notestore]	MainThread - 3104 - 10764	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:51:21	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3104 - 10764	DEBUG: 动用了Evernote API 43 次……
2018-01-17 14:52:23	ewer	everfunc.py - [<module>]	MainThread - 12496 - 14980	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:51:21,43]
2018-01-17 14:52:23	ewer	everwork.py - [<module>]	MainThread - 12496 - 14980	DEBUG: 程序启动……
2018-01-17 14:52:23	ewer	everwork.py - [<module>]	MainThread - 12496 - 14980	DEBUG: 配置文件读取成功
2018-01-17 14:52:23	ewer	everfunc.py - [wrapper]	MainThread - 12496 - 14980	DEBUG: get_notestore 启动运行
2018-01-17 14:52:24	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12496 - 14980	DEBUG: 动用了Evernote API 44 次……
2018-01-17 14:52:24	ewer	everfunc.py - [get_notestore]	MainThread - 12496 - 14980	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:52:25	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12496 - 14980	DEBUG: 动用了Evernote API 45 次……
2018-01-17 14:52:34	ewer	everfunc.py - [<module>]	MainThread - 14504 - 9268	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:52:25,45]
2018-01-17 14:52:34	ewer	everwork.py - [<module>]	MainThread - 14504 - 9268	DEBUG: 程序启动……
2018-01-17 14:52:34	ewer	everwork.py - [<module>]	MainThread - 14504 - 9268	DEBUG: 配置文件读取成功
2018-01-17 14:52:34	ewer	everfunc.py - [wrapper]	MainThread - 14504 - 9268	DEBUG: get_notestore 启动运行
2018-01-17 14:52:36	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14504 - 9268	DEBUG: 动用了Evernote API 46 次……
2018-01-17 14:52:36	ewer	everfunc.py - [get_notestore]	MainThread - 14504 - 9268	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:52:36	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14504 - 9268	DEBUG: 动用了Evernote API 47 次……
2018-01-17 14:54:59	ewer	everfunc.py - [<module>]	MainThread - 11704 - 7180	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:52:36,47]
2018-01-17 14:54:59	ewer	everwork.py - [<module>]	MainThread - 11704 - 7180	DEBUG: 程序启动……
2018-01-17 14:54:59	ewer	everwork.py - [<module>]	MainThread - 11704 - 7180	DEBUG: 配置文件读取成功
2018-01-17 14:54:59	ewer	everfunc.py - [wrapper]	MainThread - 11704 - 7180	DEBUG: get_notestore 启动运行
2018-01-17 14:55:01	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11704 - 7180	DEBUG: 动用了Evernote API 48 次……
2018-01-17 14:55:01	ewer	everfunc.py - [get_notestore]	MainThread - 11704 - 7180	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:55:01	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11704 - 7180	DEBUG: 动用了Evernote API 49 次……
2018-01-17 14:55:17	ewer	everfunc.py - [<module>]	MainThread - 1996 - 6212	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:55:01,49]
2018-01-17 14:55:17	ewer	everwork.py - [<module>]	MainThread - 1996 - 6212	DEBUG: 程序启动……
2018-01-17 14:55:17	ewer	everwork.py - [<module>]	MainThread - 1996 - 6212	DEBUG: 配置文件读取成功
2018-01-17 14:55:17	ewer	everfunc.py - [wrapper]	MainThread - 1996 - 6212	DEBUG: get_notestore 启动运行
2018-01-17 14:55:18	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1996 - 6212	DEBUG: 动用了Evernote API 50 次……
2018-01-17 14:55:18	ewer	everfunc.py - [get_notestore]	MainThread - 1996 - 6212	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:55:19	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1996 - 6212	DEBUG: 动用了Evernote API 51 次……
2018-01-17 14:56:17	ewer	everfunc.py - [<module>]	MainThread - 2892 - 940	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:55:19,51]
2018-01-17 14:56:17	ewer	everwork.py - [<module>]	MainThread - 2892 - 940	DEBUG: 程序启动……
2018-01-17 14:56:17	ewer	everwork.py - [<module>]	MainThread - 2892 - 940	DEBUG: 配置文件读取成功
2018-01-17 14:56:17	ewer	everfunc.py - [wrapper]	MainThread - 2892 - 940	DEBUG: get_notestore 启动运行
2018-01-17 14:56:19	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2892 - 940	DEBUG: 动用了Evernote API 52 次……
2018-01-17 14:56:19	ewer	everfunc.py - [get_notestore]	MainThread - 2892 - 940	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:56:20	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2892 - 940	DEBUG: 动用了Evernote API 53 次……
2018-01-17 14:56:53	ewer	everfunc.py - [<module>]	MainThread - 12108 - 15328	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:56:20,53]
2018-01-17 14:56:53	ewer	everwork.py - [<module>]	MainThread - 12108 - 15328	DEBUG: 程序启动……
2018-01-17 14:56:53	ewer	everwork.py - [<module>]	MainThread - 12108 - 15328	DEBUG: 配置文件读取成功
2018-01-17 14:56:53	ewer	everfunc.py - [wrapper]	MainThread - 12108 - 15328	DEBUG: get_notestore 启动运行
2018-01-17 14:56:55	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12108 - 15328	DEBUG: 动用了Evernote API 54 次……
2018-01-17 14:56:55	ewer	everfunc.py - [get_notestore]	MainThread - 12108 - 15328	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:56:55	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12108 - 15328	DEBUG: 动用了Evernote API 55 次……
2018-01-17 14:57:18	ewer	everfunc.py - [<module>]	MainThread - 11384 - 6872	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:56:55,55]
2018-01-17 14:57:18	ewer	everwork.py - [<module>]	MainThread - 11384 - 6872	DEBUG: 程序启动……
2018-01-17 14:57:18	ewer	everwork.py - [<module>]	MainThread - 11384 - 6872	DEBUG: 配置文件读取成功
2018-01-17 14:57:18	ewer	everfunc.py - [wrapper]	MainThread - 11384 - 6872	DEBUG: get_notestore 启动运行
2018-01-17 14:57:19	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11384 - 6872	DEBUG: 动用了Evernote API 56 次……
2018-01-17 14:57:19	ewer	everfunc.py - [get_notestore]	MainThread - 11384 - 6872	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:57:20	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11384 - 6872	DEBUG: 动用了Evernote API 57 次……
2018-01-17 14:59:04	ewer	everfunc.py - [<module>]	MainThread - 11316 - 3484	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:57:20,57]
2018-01-17 14:59:04	ewer	everwork.py - [<module>]	MainThread - 11316 - 3484	DEBUG: 程序启动……
2018-01-17 14:59:04	ewer	everwork.py - [<module>]	MainThread - 11316 - 3484	DEBUG: 配置文件读取成功
2018-01-17 14:59:04	ewer	everfunc.py - [wrapper]	MainThread - 11316 - 3484	DEBUG: get_notestore 启动运行
2018-01-17 14:59:06	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11316 - 3484	DEBUG: 动用了Evernote API 58 次……
2018-01-17 14:59:06	ewer	everfunc.py - [get_notestore]	MainThread - 11316 - 3484	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:59:06	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11316 - 3484	DEBUG: 动用了Evernote API 59 次……
2018-01-17 14:59:21	ewer	everfunc.py - [<module>]	MainThread - 9260 - 812	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:59:06,59]
2018-01-17 14:59:21	ewer	everwork.py - [<module>]	MainThread - 9260 - 812	DEBUG: 程序启动……
2018-01-17 14:59:21	ewer	everwork.py - [<module>]	MainThread - 9260 - 812	DEBUG: 配置文件读取成功
2018-01-17 14:59:21	ewer	everfunc.py - [wrapper]	MainThread - 9260 - 812	DEBUG: get_notestore 启动运行
2018-01-17 14:59:23	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9260 - 812	DEBUG: 动用了Evernote API 60 次……
2018-01-17 14:59:23	ewer	everfunc.py - [get_notestore]	MainThread - 9260 - 812	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:59:24	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9260 - 812	DEBUG: 动用了Evernote API 61 次……
2018-01-17 14:59:41	ewer	everfunc.py - [<module>]	MainThread - 10412 - 14620	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:59:24,61]
2018-01-17 14:59:41	ewer	everwork.py - [<module>]	MainThread - 10412 - 14620	DEBUG: 程序启动……
2018-01-17 14:59:41	ewer	everwork.py - [<module>]	MainThread - 10412 - 14620	DEBUG: 配置文件读取成功
2018-01-17 14:59:41	ewer	everfunc.py - [wrapper]	MainThread - 10412 - 14620	DEBUG: get_notestore 启动运行
2018-01-17 14:59:43	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10412 - 14620	DEBUG: 动用了Evernote API 62 次……
2018-01-17 14:59:43	ewer	everfunc.py - [get_notestore]	MainThread - 10412 - 14620	DEBUG: 成功连接Evernote服务器！
2018-01-17 14:59:43	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10412 - 14620	DEBUG: 动用了Evernote API 63 次……
2018-01-17 15:00:32	ewer	everfunc.py - [<module>]	MainThread - 14008 - 4964	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 14:59:43,63]
2018-01-17 15:00:32	ewer	everfunc.py - [writeini]	MainThread - 14008 - 4964	INFO: Evernote API调用次数：0，写入配置文件data\everwork.ini
2018-01-17 15:00:32	ewer	everwork.py - [<module>]	MainThread - 14008 - 4964	DEBUG: 程序启动……
2018-01-17 15:00:32	ewer	everwork.py - [<module>]	MainThread - 14008 - 4964	DEBUG: 配置文件读取成功
2018-01-17 15:00:32	ewer	everfunc.py - [wrapper]	MainThread - 14008 - 4964	DEBUG: get_notestore 启动运行
2018-01-17 15:00:34	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14008 - 4964	DEBUG: 动用了Evernote API 0 次……
2018-01-17 15:00:34	ewer	everfunc.py - [get_notestore]	MainThread - 14008 - 4964	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:00:35	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14008 - 4964	DEBUG: 动用了Evernote API 1 次……
2018-01-17 15:01:02	ewer	everfunc.py - [<module>]	MainThread - 5700 - 1112	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:00:35,1]
2018-01-17 15:01:02	ewer	everwork.py - [<module>]	MainThread - 5700 - 1112	DEBUG: 程序启动……
2018-01-17 15:01:02	ewer	everwork.py - [<module>]	MainThread - 5700 - 1112	DEBUG: 配置文件读取成功
2018-01-17 15:01:02	ewer	everfunc.py - [wrapper]	MainThread - 5700 - 1112	DEBUG: get_notestore 启动运行
2018-01-17 15:01:03	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5700 - 1112	DEBUG: 动用了Evernote API 2 次……
2018-01-17 15:01:03	ewer	everfunc.py - [get_notestore]	MainThread - 5700 - 1112	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:01:04	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5700 - 1112	DEBUG: 动用了Evernote API 3 次……
2018-01-17 15:01:37	ewer	everfunc.py - [<module>]	MainThread - 1232 - 3208	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:01:04,3]
2018-01-17 15:01:37	ewer	everwork.py - [<module>]	MainThread - 1232 - 3208	DEBUG: 程序启动……
2018-01-17 15:01:37	ewer	everwork.py - [<module>]	MainThread - 1232 - 3208	DEBUG: 配置文件读取成功
2018-01-17 15:01:37	ewer	everfunc.py - [wrapper]	MainThread - 1232 - 3208	DEBUG: get_notestore 启动运行
2018-01-17 15:01:38	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1232 - 3208	DEBUG: 动用了Evernote API 4 次……
2018-01-17 15:01:38	ewer	everfunc.py - [get_notestore]	MainThread - 1232 - 3208	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:01:40	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1232 - 3208	DEBUG: 动用了Evernote API 5 次……
2018-01-17 15:03:02	ewer	everfunc.py - [<module>]	MainThread - 6564 - 12000	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:01:40,5]
2018-01-17 15:03:02	ewer	everwork.py - [<module>]	MainThread - 6564 - 12000	DEBUG: 程序启动……
2018-01-17 15:03:02	ewer	everwork.py - [<module>]	MainThread - 6564 - 12000	DEBUG: 配置文件读取成功
2018-01-17 15:03:02	ewer	everfunc.py - [wrapper]	MainThread - 6564 - 12000	DEBUG: get_notestore 启动运行
2018-01-17 15:03:03	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 6564 - 12000	DEBUG: 动用了Evernote API 6 次……
2018-01-17 15:03:03	ewer	everfunc.py - [get_notestore]	MainThread - 6564 - 12000	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:03:04	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 6564 - 12000	DEBUG: 动用了Evernote API 7 次……
2018-01-17 15:03:20	ewer	everfunc.py - [<module>]	MainThread - 15276 - 6716	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:03:04,7]
2018-01-17 15:03:20	ewer	everwork.py - [<module>]	MainThread - 15276 - 6716	DEBUG: 程序启动……
2018-01-17 15:03:20	ewer	everwork.py - [<module>]	MainThread - 15276 - 6716	DEBUG: 配置文件读取成功
2018-01-17 15:03:20	ewer	everfunc.py - [wrapper]	MainThread - 15276 - 6716	DEBUG: get_notestore 启动运行
2018-01-17 15:03:22	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15276 - 6716	DEBUG: 动用了Evernote API 8 次……
2018-01-17 15:03:22	ewer	everfunc.py - [get_notestore]	MainThread - 15276 - 6716	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:03:22	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15276 - 6716	DEBUG: 动用了Evernote API 9 次……
2018-01-17 15:03:40	ewer	everfunc.py - [<module>]	MainThread - 12664 - 4100	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:03:22,9]
2018-01-17 15:03:40	ewer	everwork.py - [<module>]	MainThread - 12664 - 4100	DEBUG: 程序启动……
2018-01-17 15:03:40	ewer	everwork.py - [<module>]	MainThread - 12664 - 4100	DEBUG: 配置文件读取成功
2018-01-17 15:03:40	ewer	everfunc.py - [wrapper]	MainThread - 12664 - 4100	DEBUG: get_notestore 启动运行
2018-01-17 15:03:41	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12664 - 4100	DEBUG: 动用了Evernote API 10 次……
2018-01-17 15:03:41	ewer	everfunc.py - [get_notestore]	MainThread - 12664 - 4100	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:03:42	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12664 - 4100	DEBUG: 动用了Evernote API 11 次……
2018-01-17 15:04:03	ewer	everfunc.py - [<module>]	MainThread - 2736 - 12316	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:03:42,11]
2018-01-17 15:04:03	ewer	everwork.py - [<module>]	MainThread - 2736 - 12316	DEBUG: 程序启动……
2018-01-17 15:04:03	ewer	everwork.py - [<module>]	MainThread - 2736 - 12316	DEBUG: 配置文件读取成功
2018-01-17 15:04:03	ewer	everfunc.py - [wrapper]	MainThread - 2736 - 12316	DEBUG: get_notestore 启动运行
2018-01-17 15:04:04	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2736 - 12316	DEBUG: 动用了Evernote API 12 次……
2018-01-17 15:04:04	ewer	everfunc.py - [get_notestore]	MainThread - 2736 - 12316	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:04:05	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2736 - 12316	DEBUG: 动用了Evernote API 13 次……
2018-01-17 15:04:28	ewer	everfunc.py - [<module>]	MainThread - 10316 - 13620	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:04:05,13]
2018-01-17 15:04:28	ewer	everwork.py - [<module>]	MainThread - 10316 - 13620	DEBUG: 程序启动……
2018-01-17 15:04:28	ewer	everwork.py - [<module>]	MainThread - 10316 - 13620	DEBUG: 配置文件读取成功
2018-01-17 15:04:28	ewer	everfunc.py - [wrapper]	MainThread - 10316 - 13620	DEBUG: get_notestore 启动运行
2018-01-17 15:04:30	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10316 - 13620	DEBUG: 动用了Evernote API 14 次……
2018-01-17 15:04:30	ewer	everfunc.py - [get_notestore]	MainThread - 10316 - 13620	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:04:31	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10316 - 13620	DEBUG: 动用了Evernote API 15 次……
2018-01-17 15:04:56	ewer	everfunc.py - [<module>]	MainThread - 10388 - 5712	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:04:31,15]
2018-01-17 15:04:56	ewer	everwork.py - [<module>]	MainThread - 10388 - 5712	DEBUG: 程序启动……
2018-01-17 15:04:56	ewer	everwork.py - [<module>]	MainThread - 10388 - 5712	DEBUG: 配置文件读取成功
2018-01-17 15:04:56	ewer	everfunc.py - [wrapper]	MainThread - 10388 - 5712	DEBUG: get_notestore 启动运行
2018-01-17 15:04:58	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10388 - 5712	DEBUG: 动用了Evernote API 16 次……
2018-01-17 15:04:58	ewer	everfunc.py - [get_notestore]	MainThread - 10388 - 5712	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:04:58	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10388 - 5712	DEBUG: 动用了Evernote API 17 次……
2018-01-17 15:05:18	ewer	everfunc.py - [<module>]	MainThread - 5460 - 6944	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:04:58,17]
2018-01-17 15:05:18	ewer	everwork.py - [<module>]	MainThread - 5460 - 6944	DEBUG: 程序启动……
2018-01-17 15:05:18	ewer	everwork.py - [<module>]	MainThread - 5460 - 6944	DEBUG: 配置文件读取成功
2018-01-17 15:05:18	ewer	everfunc.py - [wrapper]	MainThread - 5460 - 6944	DEBUG: get_notestore 启动运行
2018-01-17 15:05:20	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5460 - 6944	DEBUG: 动用了Evernote API 18 次……
2018-01-17 15:05:20	ewer	everfunc.py - [get_notestore]	MainThread - 5460 - 6944	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:05:21	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5460 - 6944	DEBUG: 动用了Evernote API 19 次……
2018-01-17 15:06:03	ewer	everfunc.py - [<module>]	MainThread - 10432 - 6308	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:05:21,19]
2018-01-17 15:06:03	ewer	everwork.py - [<module>]	MainThread - 10432 - 6308	DEBUG: 程序启动……
2018-01-17 15:06:03	ewer	everwork.py - [<module>]	MainThread - 10432 - 6308	DEBUG: 配置文件读取成功
2018-01-17 15:06:03	ewer	everfunc.py - [wrapper]	MainThread - 10432 - 6308	DEBUG: get_notestore 启动运行
2018-01-17 15:06:05	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10432 - 6308	DEBUG: 动用了Evernote API 20 次……
2018-01-17 15:06:05	ewer	everfunc.py - [get_notestore]	MainThread - 10432 - 6308	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:06:06	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10432 - 6308	DEBUG: 动用了Evernote API 21 次……
2018-01-17 15:11:20	ewer	everfunc.py - [<module>]	MainThread - 10828 - 2912	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:06:06,21]
2018-01-17 15:11:20	ewer	everwork.py - [<module>]	MainThread - 10828 - 2912	DEBUG: 程序启动……
2018-01-17 15:11:20	ewer	everwork.py - [<module>]	MainThread - 10828 - 2912	DEBUG: 配置文件读取成功
2018-01-17 15:11:20	ewer	everfunc.py - [wrapper]	MainThread - 10828 - 2912	DEBUG: get_notestore 启动运行
2018-01-17 15:11:22	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10828 - 2912	DEBUG: 动用了Evernote API 22 次……
2018-01-17 15:11:22	ewer	everfunc.py - [get_notestore]	MainThread - 10828 - 2912	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:11:23	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10828 - 2912	DEBUG: 动用了Evernote API 23 次……
2018-01-17 15:11:38	ewer	everfunc.py - [<module>]	MainThread - 4020 - 14508	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:11:23,23]
2018-01-17 15:11:38	ewer	everwork.py - [<module>]	MainThread - 4020 - 14508	DEBUG: 程序启动……
2018-01-17 15:11:38	ewer	everwork.py - [<module>]	MainThread - 4020 - 14508	DEBUG: 配置文件读取成功
2018-01-17 15:11:38	ewer	everfunc.py - [wrapper]	MainThread - 4020 - 14508	DEBUG: get_notestore 启动运行
2018-01-17 15:11:40	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 4020 - 14508	DEBUG: 动用了Evernote API 24 次……
2018-01-17 15:11:40	ewer	everfunc.py - [get_notestore]	MainThread - 4020 - 14508	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:11:41	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 4020 - 14508	DEBUG: 动用了Evernote API 25 次……
2018-01-17 15:12:08	ewer	everfunc.py - [<module>]	MainThread - 15260 - 14616	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:11:41,25]
2018-01-17 15:12:08	ewer	everwork.py - [<module>]	MainThread - 15260 - 14616	DEBUG: 程序启动……
2018-01-17 15:12:08	ewer	everwork.py - [<module>]	MainThread - 15260 - 14616	DEBUG: 配置文件读取成功
2018-01-17 15:12:08	ewer	everfunc.py - [wrapper]	MainThread - 15260 - 14616	DEBUG: get_notestore 启动运行
2018-01-17 15:12:10	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15260 - 14616	DEBUG: 动用了Evernote API 26 次……
2018-01-17 15:12:10	ewer	everfunc.py - [get_notestore]	MainThread - 15260 - 14616	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:12:11	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15260 - 14616	DEBUG: 动用了Evernote API 27 次……
2018-01-17 15:14:42	ewer	everfunc.py - [<module>]	MainThread - 4440 - 9744	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:12:11,27]
2018-01-17 15:14:42	ewer	everwork.py - [<module>]	MainThread - 4440 - 9744	DEBUG: 程序启动……
2018-01-17 15:14:42	ewer	everwork.py - [<module>]	MainThread - 4440 - 9744	DEBUG: 配置文件读取成功
2018-01-17 15:14:42	ewer	everfunc.py - [wrapper]	MainThread - 4440 - 9744	DEBUG: get_notestore 启动运行
2018-01-17 15:14:44	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 4440 - 9744	DEBUG: 动用了Evernote API 28 次……
2018-01-17 15:14:44	ewer	everfunc.py - [get_notestore]	MainThread - 4440 - 9744	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:14:45	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 4440 - 9744	DEBUG: 动用了Evernote API 29 次……
2018-01-17 15:15:05	ewer	everfunc.py - [<module>]	MainThread - 2012 - 14404	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:14:45,29]
2018-01-17 15:15:05	ewer	everwork.py - [<module>]	MainThread - 2012 - 14404	DEBUG: 程序启动……
2018-01-17 15:15:05	ewer	everwork.py - [<module>]	MainThread - 2012 - 14404	DEBUG: 配置文件读取成功
2018-01-17 15:15:05	ewer	everfunc.py - [wrapper]	MainThread - 2012 - 14404	DEBUG: get_notestore 启动运行
2018-01-17 15:15:06	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2012 - 14404	DEBUG: 动用了Evernote API 30 次……
2018-01-17 15:15:06	ewer	everfunc.py - [get_notestore]	MainThread - 2012 - 14404	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:15:07	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2012 - 14404	DEBUG: 动用了Evernote API 31 次……
2018-01-17 15:15:42	ewer	everfunc.py - [<module>]	MainThread - 14864 - 2084	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:15:07,31]
2018-01-17 15:15:42	ewer	everwork.py - [<module>]	MainThread - 14864 - 2084	DEBUG: 程序启动……
2018-01-17 15:15:42	ewer	everwork.py - [<module>]	MainThread - 14864 - 2084	DEBUG: 配置文件读取成功
2018-01-17 15:15:42	ewer	everfunc.py - [wrapper]	MainThread - 14864 - 2084	DEBUG: get_notestore 启动运行
2018-01-17 15:15:44	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14864 - 2084	DEBUG: 动用了Evernote API 32 次……
2018-01-17 15:15:44	ewer	everfunc.py - [get_notestore]	MainThread - 14864 - 2084	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:15:45	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14864 - 2084	DEBUG: 动用了Evernote API 33 次……
2018-01-17 15:16:39	ewer	everfunc.py - [<module>]	MainThread - 14824 - 12832	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:15:45,33]
2018-01-17 15:16:39	ewer	everwork.py - [<module>]	MainThread - 14824 - 12832	DEBUG: 程序启动……
2018-01-17 15:16:39	ewer	everwork.py - [<module>]	MainThread - 14824 - 12832	DEBUG: 配置文件读取成功
2018-01-17 15:16:39	ewer	everfunc.py - [wrapper]	MainThread - 14824 - 12832	DEBUG: get_notestore 启动运行
2018-01-17 15:16:40	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14824 - 12832	DEBUG: 动用了Evernote API 34 次……
2018-01-17 15:16:40	ewer	everfunc.py - [get_notestore]	MainThread - 14824 - 12832	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:16:41	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14824 - 12832	DEBUG: 动用了Evernote API 35 次……
2018-01-17 15:17:49	ewer	everfunc.py - [<module>]	MainThread - 5656 - 14356	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:16:41,35]
2018-01-17 15:17:49	ewer	everwork.py - [<module>]	MainThread - 5656 - 14356	DEBUG: 程序启动……
2018-01-17 15:17:49	ewer	everwork.py - [<module>]	MainThread - 5656 - 14356	DEBUG: 配置文件读取成功
2018-01-17 15:17:49	ewer	everfunc.py - [wrapper]	MainThread - 5656 - 14356	DEBUG: get_notestore 启动运行
2018-01-17 15:17:51	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5656 - 14356	DEBUG: 动用了Evernote API 36 次……
2018-01-17 15:17:51	ewer	everfunc.py - [get_notestore]	MainThread - 5656 - 14356	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:17:53	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5656 - 14356	DEBUG: 动用了Evernote API 37 次……
2018-01-17 15:17:58	ewer	everfunc.py - [writeini]	MainThread - 5656 - 14356	INFO: Evernote API调用次数：38，写入配置文件data\everwork.ini
2018-01-17 15:17:58	ewer	everwork.py - [<module>]	MainThread - 5656 - 14356	DEBUG: 程序结束！
2018-01-17 15:18:16	ewer	everwork.py - [<module>]	MainThread - 9916 - 12972	DEBUG: 程序启动……
2018-01-17 15:18:16	ewer	everwork.py - [<module>]	MainThread - 9916 - 12972	DEBUG: 配置文件读取成功
2018-01-17 15:18:16	ewer	everfunc.py - [wrapper]	MainThread - 9916 - 12972	DEBUG: get_notestore 启动运行
2018-01-17 15:18:18	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9916 - 12972	DEBUG: 动用了Evernote API 38 次……
2018-01-17 15:18:18	ewer	everfunc.py - [get_notestore]	MainThread - 9916 - 12972	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:18:18	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9916 - 12972	DEBUG: 动用了Evernote API 39 次……
2018-01-17 15:18:34	ewer	everfunc.py - [writeini]	MainThread - 9916 - 12972	INFO: Evernote API调用次数：40，写入配置文件data\everwork.ini
2018-01-17 15:18:34	ewer	everwork.py - [<module>]	MainThread - 9916 - 12972	DEBUG: 程序结束！
2018-01-17 15:19:17	ewer	everwork.py - [<module>]	MainThread - 13412 - 11388	DEBUG: 程序启动……
2018-01-17 15:19:17	ewer	everwork.py - [<module>]	MainThread - 13412 - 11388	DEBUG: 配置文件读取成功
2018-01-17 15:19:17	ewer	everfunc.py - [wrapper]	MainThread - 13412 - 11388	DEBUG: get_notestore 启动运行
2018-01-17 15:19:19	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13412 - 11388	DEBUG: 动用了Evernote API 40 次……
2018-01-17 15:19:19	ewer	everfunc.py - [get_notestore]	MainThread - 13412 - 11388	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:19:19	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13412 - 11388	DEBUG: 动用了Evernote API 41 次……
2018-01-17 15:19:22	ewer	everfunc.py - [writeini]	MainThread - 13412 - 11388	INFO: Evernote API调用次数：42，写入配置文件data\everwork.ini
2018-01-17 15:19:22	ewer	everwork.py - [<module>]	MainThread - 13412 - 11388	DEBUG: 程序结束！
2018-01-17 15:21:19	ewer	everwork.py - [<module>]	MainThread - 3128 - 12076	DEBUG: 程序启动……
2018-01-17 15:21:19	ewer	everwork.py - [<module>]	MainThread - 3128 - 12076	DEBUG: 配置文件读取成功
2018-01-17 15:21:19	ewer	everfunc.py - [wrapper]	MainThread - 3128 - 12076	DEBUG: get_notestore 启动运行
2018-01-17 15:21:21	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3128 - 12076	DEBUG: 动用了Evernote API 42 次……
2018-01-17 15:21:21	ewer	everfunc.py - [get_notestore]	MainThread - 3128 - 12076	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:21:22	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3128 - 12076	DEBUG: 动用了Evernote API 43 次……
2018-01-17 15:22:15	ewer	everfunc.py - [<module>]	MainThread - 13872 - 12456	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:21:22,43]
2018-01-17 15:22:15	ewer	everwork.py - [<module>]	MainThread - 13872 - 12456	DEBUG: 程序启动……
2018-01-17 15:22:15	ewer	everwork.py - [<module>]	MainThread - 13872 - 12456	DEBUG: 配置文件读取成功
2018-01-17 15:22:15	ewer	everfunc.py - [wrapper]	MainThread - 13872 - 12456	DEBUG: get_notestore 启动运行
2018-01-17 15:22:17	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13872 - 12456	DEBUG: 动用了Evernote API 44 次……
2018-01-17 15:22:17	ewer	everfunc.py - [get_notestore]	MainThread - 13872 - 12456	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:22:17	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13872 - 12456	DEBUG: 动用了Evernote API 45 次……
2018-01-17 15:23:15	ewer	everfunc.py - [writeini]	MainThread - 13872 - 12456	INFO: Evernote API调用次数：46，写入配置文件data\everwork.ini
2018-01-17 15:23:15	ewer	everwork.py - [<module>]	MainThread - 13872 - 12456	DEBUG: 程序结束！
2018-01-17 15:23:25	ewer	everwork.py - [<module>]	MainThread - 5920 - 7904	DEBUG: 程序启动……
2018-01-17 15:23:25	ewer	everwork.py - [<module>]	MainThread - 5920 - 7904	DEBUG: 配置文件读取成功
2018-01-17 15:23:25	ewer	everfunc.py - [wrapper]	MainThread - 5920 - 7904	DEBUG: get_notestore 启动运行
2018-01-17 15:23:27	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5920 - 7904	DEBUG: 动用了Evernote API 46 次……
2018-01-17 15:23:27	ewer	everfunc.py - [get_notestore]	MainThread - 5920 - 7904	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:23:27	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5920 - 7904	DEBUG: 动用了Evernote API 47 次……
2018-01-17 15:25:52	ewer	everfunc.py - [<module>]	MainThread - 5356 - 2760	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:23:27,47]
2018-01-17 15:25:52	ewer	everwork.py - [<module>]	MainThread - 5356 - 2760	DEBUG: 程序启动……
2018-01-17 15:25:52	ewer	everwork.py - [<module>]	MainThread - 5356 - 2760	DEBUG: 配置文件读取成功
2018-01-17 15:25:52	ewer	everfunc.py - [wrapper]	MainThread - 5356 - 2760	DEBUG: get_notestore 启动运行
2018-01-17 15:25:54	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5356 - 2760	DEBUG: 动用了Evernote API 48 次……
2018-01-17 15:25:54	ewer	everfunc.py - [get_notestore]	MainThread - 5356 - 2760	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:25:54	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5356 - 2760	DEBUG: 动用了Evernote API 49 次……
2018-01-17 15:26:39	ewer	everfunc.py - [writeini]	MainThread - 5356 - 2760	INFO: Evernote API调用次数：50，写入配置文件data\everwork.ini
2018-01-17 15:26:39	ewer	everwork.py - [<module>]	MainThread - 5356 - 2760	DEBUG: 程序结束！
2018-01-17 15:26:58	ewer	everwork.py - [<module>]	MainThread - 6404 - 7140	DEBUG: 程序启动……
2018-01-17 15:26:58	ewer	everwork.py - [<module>]	MainThread - 6404 - 7140	DEBUG: 配置文件读取成功
2018-01-17 15:26:58	ewer	everfunc.py - [wrapper]	MainThread - 6404 - 7140	DEBUG: get_notestore 启动运行
2018-01-17 15:26:59	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 6404 - 7140	DEBUG: 动用了Evernote API 50 次……
2018-01-17 15:26:59	ewer	everfunc.py - [get_notestore]	MainThread - 6404 - 7140	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:27:00	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 6404 - 7140	DEBUG: 动用了Evernote API 51 次……
2018-01-17 15:27:17	ewer	everfunc.py - [writeini]	MainThread - 6404 - 7140	INFO: Evernote API调用次数：52，写入配置文件data\everwork.ini
2018-01-17 15:27:17	ewer	everwork.py - [<module>]	MainThread - 6404 - 7140	DEBUG: 程序结束！
2018-01-17 15:27:31	ewer	everwork.py - [<module>]	MainThread - 5180 - 8380	DEBUG: 程序启动……
2018-01-17 15:27:31	ewer	everwork.py - [<module>]	MainThread - 5180 - 8380	DEBUG: 配置文件读取成功
2018-01-17 15:27:31	ewer	everfunc.py - [wrapper]	MainThread - 5180 - 8380	DEBUG: get_notestore 启动运行
2018-01-17 15:27:32	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5180 - 8380	DEBUG: 动用了Evernote API 52 次……
2018-01-17 15:27:32	ewer	everfunc.py - [get_notestore]	MainThread - 5180 - 8380	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:27:33	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5180 - 8380	DEBUG: 动用了Evernote API 53 次……
2018-01-17 15:28:23	ewer	everfunc.py - [writeini]	MainThread - 5180 - 8380	INFO: Evernote API调用次数：54，写入配置文件data\everwork.ini
2018-01-17 15:28:23	ewer	everwork.py - [<module>]	MainThread - 5180 - 8380	DEBUG: 程序结束！
2018-01-17 15:30:09	ewer	everwork.py - [<module>]	MainThread - 15260 - 6708	DEBUG: 程序启动……
2018-01-17 15:30:09	ewer	everwork.py - [<module>]	MainThread - 15260 - 6708	DEBUG: 配置文件读取成功
2018-01-17 15:30:09	ewer	everfunc.py - [wrapper]	MainThread - 15260 - 6708	DEBUG: get_notestore 启动运行
2018-01-17 15:30:10	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15260 - 6708	DEBUG: 动用了Evernote API 54 次……
2018-01-17 15:30:10	ewer	everfunc.py - [get_notestore]	MainThread - 15260 - 6708	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:30:11	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15260 - 6708	DEBUG: 动用了Evernote API 55 次……
2018-01-17 15:30:22	ewer	everfunc.py - [<module>]	MainThread - 12972 - 5736	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:30:11,55]
2018-01-17 15:30:22	ewer	everwork.py - [<module>]	MainThread - 12972 - 5736	DEBUG: 程序启动……
2018-01-17 15:30:22	ewer	everwork.py - [<module>]	MainThread - 12972 - 5736	DEBUG: 配置文件读取成功
2018-01-17 15:30:22	ewer	everfunc.py - [wrapper]	MainThread - 12972 - 5736	DEBUG: get_notestore 启动运行
2018-01-17 15:30:23	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12972 - 5736	DEBUG: 动用了Evernote API 56 次……
2018-01-17 15:30:23	ewer	everfunc.py - [get_notestore]	MainThread - 12972 - 5736	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:30:24	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12972 - 5736	DEBUG: 动用了Evernote API 57 次……
2018-01-17 15:30:39	ewer	everfunc.py - [<module>]	MainThread - 1820 - 15284	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:30:24,57]
2018-01-17 15:30:39	ewer	everwork.py - [<module>]	MainThread - 1820 - 15284	DEBUG: 程序启动……
2018-01-17 15:30:39	ewer	everwork.py - [<module>]	MainThread - 1820 - 15284	DEBUG: 配置文件读取成功
2018-01-17 15:30:39	ewer	everfunc.py - [wrapper]	MainThread - 1820 - 15284	DEBUG: get_notestore 启动运行
2018-01-17 15:30:41	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1820 - 15284	DEBUG: 动用了Evernote API 58 次……
2018-01-17 15:30:41	ewer	everfunc.py - [get_notestore]	MainThread - 1820 - 15284	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:30:42	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1820 - 15284	DEBUG: 动用了Evernote API 59 次……
2018-01-17 15:31:37	ewer	everfunc.py - [<module>]	MainThread - 14820 - 5504	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:30:42,59]
2018-01-17 15:31:37	ewer	everwork.py - [<module>]	MainThread - 14820 - 5504	DEBUG: 程序启动……
2018-01-17 15:31:37	ewer	everwork.py - [<module>]	MainThread - 14820 - 5504	DEBUG: 配置文件读取成功
2018-01-17 15:31:37	ewer	everfunc.py - [wrapper]	MainThread - 14820 - 5504	DEBUG: get_notestore 启动运行
2018-01-17 15:31:38	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14820 - 5504	DEBUG: 动用了Evernote API 60 次……
2018-01-17 15:31:38	ewer	everfunc.py - [get_notestore]	MainThread - 14820 - 5504	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:31:39	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14820 - 5504	DEBUG: 动用了Evernote API 61 次……
2018-01-17 15:31:57	ewer	everfunc.py - [<module>]	MainThread - 13872 - 2572	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:31:39,61]
2018-01-17 15:31:57	ewer	everwork.py - [<module>]	MainThread - 13872 - 2572	DEBUG: 程序启动……
2018-01-17 15:31:57	ewer	everwork.py - [<module>]	MainThread - 13872 - 2572	DEBUG: 配置文件读取成功
2018-01-17 15:31:57	ewer	everfunc.py - [wrapper]	MainThread - 13872 - 2572	DEBUG: get_notestore 启动运行
2018-01-17 15:31:59	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13872 - 2572	DEBUG: 动用了Evernote API 62 次……
2018-01-17 15:31:59	ewer	everfunc.py - [get_notestore]	MainThread - 13872 - 2572	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:31:59	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13872 - 2572	DEBUG: 动用了Evernote API 63 次……
2018-01-17 15:32:25	ewer	everfunc.py - [writeini]	MainThread - 13872 - 2572	INFO: Evernote API调用次数：64，写入配置文件data\everwork.ini
2018-01-17 15:32:25	ewer	everwork.py - [<module>]	MainThread - 13872 - 2572	DEBUG: 程序结束！
2018-01-17 15:33:32	ewer	everwork.py - [<module>]	MainThread - 12208 - 13260	DEBUG: 程序启动……
2018-01-17 15:33:32	ewer	everwork.py - [<module>]	MainThread - 12208 - 13260	DEBUG: 配置文件读取成功
2018-01-17 15:33:32	ewer	everfunc.py - [wrapper]	MainThread - 12208 - 13260	DEBUG: get_notestore 启动运行
2018-01-17 15:33:34	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12208 - 13260	DEBUG: 动用了Evernote API 64 次……
2018-01-17 15:33:34	ewer	everfunc.py - [get_notestore]	MainThread - 12208 - 13260	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:33:35	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12208 - 13260	DEBUG: 动用了Evernote API 65 次……
2018-01-17 15:34:31	ewer	everfunc.py - [<module>]	MainThread - 9320 - 4324	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:33:35,65]
2018-01-17 15:34:31	ewer	everwork.py - [<module>]	MainThread - 9320 - 4324	DEBUG: 程序启动……
2018-01-17 15:34:31	ewer	everwork.py - [<module>]	MainThread - 9320 - 4324	DEBUG: 配置文件读取成功
2018-01-17 15:34:31	ewer	everfunc.py - [wrapper]	MainThread - 9320 - 4324	DEBUG: get_notestore 启动运行
2018-01-17 15:34:33	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9320 - 4324	DEBUG: 动用了Evernote API 66 次……
2018-01-17 15:34:33	ewer	everfunc.py - [get_notestore]	MainThread - 9320 - 4324	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:34:34	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9320 - 4324	DEBUG: 动用了Evernote API 67 次……
2018-01-17 15:34:39	ewer	everfunc.py - [writeini]	MainThread - 9320 - 4324	INFO: Evernote API调用次数：68，写入配置文件data\everwork.ini
2018-01-17 15:34:39	ewer	everwork.py - [<module>]	MainThread - 9320 - 4324	DEBUG: 程序结束！
2018-01-17 15:42:07	ewer	everwork.py - [<module>]	MainThread - 12144 - 8828	DEBUG: 程序启动……
2018-01-17 15:42:07	ewer	everwork.py - [<module>]	MainThread - 12144 - 8828	DEBUG: 配置文件读取成功
2018-01-17 15:42:07	ewer	everfunc.py - [wrapper]	MainThread - 12144 - 8828	DEBUG: get_notestore 启动运行
2018-01-17 15:42:09	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12144 - 8828	DEBUG: 动用了Evernote API 68 次……
2018-01-17 15:42:09	ewer	everfunc.py - [get_notestore]	MainThread - 12144 - 8828	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:42:10	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12144 - 8828	DEBUG: 动用了Evernote API 69 次……
2018-01-17 15:42:37	ewer	everfunc.py - [writeini]	MainThread - 12144 - 8828	INFO: Evernote API调用次数：70，写入配置文件data\everwork.ini
2018-01-17 15:42:37	ewer	everwork.py - [<module>]	MainThread - 12144 - 8828	DEBUG: 程序结束！
2018-01-17 15:42:45	ewer	everwork.py - [<module>]	MainThread - 5692 - 11336	DEBUG: 程序启动……
2018-01-17 15:42:45	ewer	everwork.py - [<module>]	MainThread - 5692 - 11336	DEBUG: 配置文件读取成功
2018-01-17 15:42:45	ewer	everfunc.py - [wrapper]	MainThread - 5692 - 11336	DEBUG: get_notestore 启动运行
2018-01-17 15:42:47	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5692 - 11336	DEBUG: 动用了Evernote API 70 次……
2018-01-17 15:42:47	ewer	everfunc.py - [get_notestore]	MainThread - 5692 - 11336	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:42:48	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5692 - 11336	DEBUG: 动用了Evernote API 71 次……
2018-01-17 15:43:03	ewer	everfunc.py - [<module>]	MainThread - 15188 - 6648	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 15:42:48,71]
2018-01-17 15:43:03	ewer	everwork.py - [<module>]	MainThread - 15188 - 6648	DEBUG: 程序启动……
2018-01-17 15:43:03	ewer	everwork.py - [<module>]	MainThread - 15188 - 6648	DEBUG: 配置文件读取成功
2018-01-17 15:43:03	ewer	everfunc.py - [wrapper]	MainThread - 15188 - 6648	DEBUG: get_notestore 启动运行
2018-01-17 15:43:04	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15188 - 6648	DEBUG: 动用了Evernote API 72 次……
2018-01-17 15:43:04	ewer	everfunc.py - [get_notestore]	MainThread - 15188 - 6648	DEBUG: 成功连接Evernote服务器！
2018-01-17 15:43:05	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15188 - 6648	DEBUG: 动用了Evernote API 73 次……
2018-01-17 15:43:13	ewer	everfunc.py - [writeini]	MainThread - 15188 - 6648	INFO: Evernote API调用次数：74，写入配置文件data\everwork.ini
2018-01-17 15:43:13	ewer	everwork.py - [<module>]	MainThread - 15188 - 6648	DEBUG: 程序结束！
2018-01-17 16:36:31	ewer	everfunc.py - [writeini]	MainThread - 9740 - 10700	INFO: Evernote API调用次数：0，写入配置文件data\everwork.ini
2018-01-17 16:36:31	ewer	everwork.py - [<module>]	MainThread - 9740 - 10700	DEBUG: 程序启动……
2018-01-17 16:36:31	ewer	everwork.py - [<module>]	MainThread - 9740 - 10700	DEBUG: 配置文件读取成功
2018-01-17 16:36:31	ewer	everfunc.py - [wrapper]	MainThread - 9740 - 10700	DEBUG: get_notestore 启动运行
2018-01-17 16:36:33	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9740 - 10700	DEBUG: 动用了Evernote API 0 次……
2018-01-17 16:36:33	ewer	everfunc.py - [get_notestore]	MainThread - 9740 - 10700	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:36:33	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9740 - 10700	DEBUG: 动用了Evernote API 1 次……
2018-01-17 16:36:33	ewer	everfunc.py - [writeini]	MainThread - 9740 - 10700	INFO: Evernote API调用次数：2，写入配置文件data\everwork.ini
2018-01-17 16:36:33	ewer	everwork.py - [<module>]	MainThread - 9740 - 10700	DEBUG: 程序结束！
2018-01-17 16:37:44	ewer	everwork.py - [<module>]	MainThread - 8792 - 10828	DEBUG: 程序启动……
2018-01-17 16:37:44	ewer	everwork.py - [<module>]	MainThread - 8792 - 10828	DEBUG: 配置文件读取成功
2018-01-17 16:37:44	ewer	everfunc.py - [wrapper]	MainThread - 8792 - 10828	DEBUG: get_notestore 启动运行
2018-01-17 16:37:46	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8792 - 10828	DEBUG: 动用了Evernote API 2 次……
2018-01-17 16:37:46	ewer	everfunc.py - [get_notestore]	MainThread - 8792 - 10828	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:37:46	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8792 - 10828	DEBUG: 动用了Evernote API 3 次……
2018-01-17 16:38:05	ewer	everfunc.py - [writeini]	MainThread - 8792 - 10828	INFO: Evernote API调用次数：4，写入配置文件data\everwork.ini
2018-01-17 16:38:05	ewer	everwork.py - [<module>]	MainThread - 8792 - 10828	DEBUG: 程序结束！
2018-01-17 16:38:13	ewer	everwork.py - [<module>]	MainThread - 12476 - 14660	DEBUG: 程序启动……
2018-01-17 16:38:13	ewer	everwork.py - [<module>]	MainThread - 12476 - 14660	DEBUG: 配置文件读取成功
2018-01-17 16:38:13	ewer	everfunc.py - [wrapper]	MainThread - 12476 - 14660	DEBUG: get_notestore 启动运行
2018-01-17 16:38:15	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12476 - 14660	DEBUG: 动用了Evernote API 4 次……
2018-01-17 16:38:15	ewer	everfunc.py - [get_notestore]	MainThread - 12476 - 14660	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:38:15	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12476 - 14660	DEBUG: 动用了Evernote API 5 次……
2018-01-17 16:38:26	ewer	everfunc.py - [writeini]	MainThread - 12476 - 14660	INFO: Evernote API调用次数：6，写入配置文件data\everwork.ini
2018-01-17 16:38:26	ewer	everwork.py - [<module>]	MainThread - 12476 - 14660	DEBUG: 程序结束！
2018-01-17 16:38:48	ewer	everwork.py - [<module>]	MainThread - 2096 - 11820	DEBUG: 程序启动……
2018-01-17 16:38:48	ewer	everwork.py - [<module>]	MainThread - 2096 - 11820	DEBUG: 配置文件读取成功
2018-01-17 16:38:48	ewer	everfunc.py - [wrapper]	MainThread - 2096 - 11820	DEBUG: get_notestore 启动运行
2018-01-17 16:38:49	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2096 - 11820	DEBUG: 动用了Evernote API 6 次……
2018-01-17 16:38:49	ewer	everfunc.py - [get_notestore]	MainThread - 2096 - 11820	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:38:50	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2096 - 11820	DEBUG: 动用了Evernote API 7 次……
2018-01-17 16:39:06	ewer	everfunc.py - [<module>]	MainThread - 2320 - 11156	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 16:38:50,7]
2018-01-17 16:39:06	ewer	everwork.py - [<module>]	MainThread - 2320 - 11156	DEBUG: 程序启动……
2018-01-17 16:39:06	ewer	everwork.py - [<module>]	MainThread - 2320 - 11156	DEBUG: 配置文件读取成功
2018-01-17 16:39:06	ewer	everfunc.py - [wrapper]	MainThread - 2320 - 11156	DEBUG: get_notestore 启动运行
2018-01-17 16:39:08	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2320 - 11156	DEBUG: 动用了Evernote API 8 次……
2018-01-17 16:39:08	ewer	everfunc.py - [get_notestore]	MainThread - 2320 - 11156	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:39:08	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2320 - 11156	DEBUG: 动用了Evernote API 9 次……
2018-01-17 16:39:34	ewer	everfunc.py - [<module>]	MainThread - 14420 - 11816	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 16:39:08,9]
2018-01-17 16:39:34	ewer	everwork.py - [<module>]	MainThread - 14420 - 11816	DEBUG: 程序启动……
2018-01-17 16:39:34	ewer	everwork.py - [<module>]	MainThread - 14420 - 11816	DEBUG: 配置文件读取成功
2018-01-17 16:39:34	ewer	everfunc.py - [wrapper]	MainThread - 14420 - 11816	DEBUG: get_notestore 启动运行
2018-01-17 16:39:35	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14420 - 11816	DEBUG: 动用了Evernote API 10 次……
2018-01-17 16:39:35	ewer	everfunc.py - [get_notestore]	MainThread - 14420 - 11816	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:39:36	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14420 - 11816	DEBUG: 动用了Evernote API 11 次……
2018-01-17 16:40:00	ewer	everfunc.py - [writeini]	MainThread - 14420 - 11816	INFO: Evernote API调用次数：12，写入配置文件data\everwork.ini
2018-01-17 16:40:00	ewer	everwork.py - [<module>]	MainThread - 14420 - 11816	DEBUG: 程序结束！
2018-01-17 16:40:21	ewer	everwork.py - [<module>]	MainThread - 14204 - 2620	DEBUG: 程序启动……
2018-01-17 16:40:21	ewer	everwork.py - [<module>]	MainThread - 14204 - 2620	DEBUG: 配置文件读取成功
2018-01-17 16:40:21	ewer	everfunc.py - [wrapper]	MainThread - 14204 - 2620	DEBUG: get_notestore 启动运行
2018-01-17 16:40:23	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14204 - 2620	DEBUG: 动用了Evernote API 12 次……
2018-01-17 16:40:23	ewer	everfunc.py - [get_notestore]	MainThread - 14204 - 2620	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:40:24	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14204 - 2620	DEBUG: 动用了Evernote API 13 次……
2018-01-17 16:40:38	ewer	everfunc.py - [writeini]	MainThread - 14204 - 2620	INFO: Evernote API调用次数：14，写入配置文件data\everwork.ini
2018-01-17 16:40:38	ewer	everwork.py - [<module>]	MainThread - 14204 - 2620	DEBUG: 程序结束！
2018-01-17 16:41:08	ewer	everwork.py - [<module>]	MainThread - 13060 - 2572	DEBUG: 程序启动……
2018-01-17 16:41:08	ewer	everwork.py - [<module>]	MainThread - 13060 - 2572	DEBUG: 配置文件读取成功
2018-01-17 16:41:08	ewer	everfunc.py - [wrapper]	MainThread - 13060 - 2572	DEBUG: get_notestore 启动运行
2018-01-17 16:41:09	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13060 - 2572	DEBUG: 动用了Evernote API 14 次……
2018-01-17 16:41:09	ewer	everfunc.py - [get_notestore]	MainThread - 13060 - 2572	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:41:10	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13060 - 2572	DEBUG: 动用了Evernote API 15 次……
2018-01-17 16:41:27	ewer	everfunc.py - [writeini]	MainThread - 13060 - 2572	INFO: Evernote API调用次数：16，写入配置文件data\everwork.ini
2018-01-17 16:41:27	ewer	everwork.py - [<module>]	MainThread - 13060 - 2572	DEBUG: 程序结束！
2018-01-17 16:42:00	ewer	everwork.py - [<module>]	MainThread - 10368 - 14916	DEBUG: 程序启动……
2018-01-17 16:42:00	ewer	everwork.py - [<module>]	MainThread - 10368 - 14916	DEBUG: 配置文件读取成功
2018-01-17 16:42:00	ewer	everfunc.py - [wrapper]	MainThread - 10368 - 14916	DEBUG: get_notestore 启动运行
2018-01-17 16:42:02	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10368 - 14916	DEBUG: 动用了Evernote API 16 次……
2018-01-17 16:42:02	ewer	everfunc.py - [get_notestore]	MainThread - 10368 - 14916	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:42:03	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10368 - 14916	DEBUG: 动用了Evernote API 17 次……
2018-01-17 16:42:14	ewer	everfunc.py - [writeini]	MainThread - 10368 - 14916	INFO: Evernote API调用次数：18，写入配置文件data\everwork.ini
2018-01-17 16:42:14	ewer	everwork.py - [<module>]	MainThread - 10368 - 14916	DEBUG: 程序结束！
2018-01-17 16:42:53	ewer	everwork.py - [<module>]	MainThread - 14504 - 1512	DEBUG: 程序启动……
2018-01-17 16:42:53	ewer	everwork.py - [<module>]	MainThread - 14504 - 1512	DEBUG: 配置文件读取成功
2018-01-17 16:42:53	ewer	everfunc.py - [wrapper]	MainThread - 14504 - 1512	DEBUG: get_notestore 启动运行
2018-01-17 16:42:55	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14504 - 1512	DEBUG: 动用了Evernote API 18 次……
2018-01-17 16:42:55	ewer	everfunc.py - [get_notestore]	MainThread - 14504 - 1512	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:42:55	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14504 - 1512	DEBUG: 动用了Evernote API 19 次……
2018-01-17 16:42:59	ewer	everfunc.py - [writeini]	MainThread - 14504 - 1512	INFO: Evernote API调用次数：20，写入配置文件data\everwork.ini
2018-01-17 16:42:59	ewer	everwork.py - [<module>]	MainThread - 14504 - 1512	DEBUG: 程序结束！
2018-01-17 16:43:16	ewer	everwork.py - [<module>]	MainThread - 12356 - 11340	DEBUG: 程序启动……
2018-01-17 16:43:16	ewer	everwork.py - [<module>]	MainThread - 12356 - 11340	DEBUG: 配置文件读取成功
2018-01-17 16:43:16	ewer	everfunc.py - [wrapper]	MainThread - 12356 - 11340	DEBUG: get_notestore 启动运行
2018-01-17 16:43:18	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12356 - 11340	DEBUG: 动用了Evernote API 20 次……
2018-01-17 16:43:18	ewer	everfunc.py - [get_notestore]	MainThread - 12356 - 11340	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:43:19	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12356 - 11340	DEBUG: 动用了Evernote API 21 次……
2018-01-17 16:45:08	ewer	everfunc.py - [writeini]	MainThread - 12356 - 11340	INFO: Evernote API调用次数：22，写入配置文件data\everwork.ini
2018-01-17 16:45:08	ewer	everwork.py - [<module>]	MainThread - 12356 - 11340	DEBUG: 程序结束！
2018-01-17 16:45:15	ewer	everwork.py - [<module>]	MainThread - 6340 - 8640	DEBUG: 程序启动……
2018-01-17 16:45:15	ewer	everwork.py - [<module>]	MainThread - 6340 - 8640	DEBUG: 配置文件读取成功
2018-01-17 16:45:15	ewer	everfunc.py - [wrapper]	MainThread - 6340 - 8640	DEBUG: get_notestore 启动运行
2018-01-17 16:45:17	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 6340 - 8640	DEBUG: 动用了Evernote API 22 次……
2018-01-17 16:45:17	ewer	everfunc.py - [get_notestore]	MainThread - 6340 - 8640	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:45:18	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 6340 - 8640	DEBUG: 动用了Evernote API 23 次……
2018-01-17 16:45:33	ewer	everfunc.py - [writeini]	MainThread - 6340 - 8640	INFO: Evernote API调用次数：24，写入配置文件data\everwork.ini
2018-01-17 16:45:33	ewer	everwork.py - [<module>]	MainThread - 6340 - 8640	DEBUG: 程序结束！
2018-01-17 16:51:23	ewer	everwork.py - [<module>]	MainThread - 8932 - 6604	DEBUG: 程序启动……
2018-01-17 16:51:23	ewer	everwork.py - [<module>]	MainThread - 8932 - 6604	DEBUG: 配置文件读取成功
2018-01-17 16:51:23	ewer	everfunc.py - [wrapper]	MainThread - 8932 - 6604	DEBUG: get_notestore 启动运行
2018-01-17 16:51:24	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8932 - 6604	DEBUG: 动用了Evernote API 24 次……
2018-01-17 16:51:24	ewer	everfunc.py - [get_notestore]	MainThread - 8932 - 6604	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:51:25	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8932 - 6604	DEBUG: 动用了Evernote API 25 次……
2018-01-17 16:51:57	ewer	everfunc.py - [<module>]	MainThread - 9180 - 6476	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 16:51:25,25]
2018-01-17 16:51:57	ewer	everwork.py - [<module>]	MainThread - 9180 - 6476	DEBUG: 程序启动……
2018-01-17 16:51:57	ewer	everwork.py - [<module>]	MainThread - 9180 - 6476	DEBUG: 配置文件读取成功
2018-01-17 16:51:57	ewer	everfunc.py - [wrapper]	MainThread - 9180 - 6476	DEBUG: get_notestore 启动运行
2018-01-17 16:51:59	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9180 - 6476	DEBUG: 动用了Evernote API 26 次……
2018-01-17 16:51:59	ewer	everfunc.py - [get_notestore]	MainThread - 9180 - 6476	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:52:00	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9180 - 6476	DEBUG: 动用了Evernote API 27 次……
2018-01-17 16:52:08	ewer	everfunc.py - [writeini]	MainThread - 9180 - 6476	INFO: Evernote API调用次数：28，写入配置文件data\everwork.ini
2018-01-17 16:52:08	ewer	everwork.py - [<module>]	MainThread - 9180 - 6476	DEBUG: 程序结束！
2018-01-17 16:53:19	ewer	everwork.py - [<module>]	MainThread - 12080 - 7288	DEBUG: 程序启动……
2018-01-17 16:53:19	ewer	everwork.py - [<module>]	MainThread - 12080 - 7288	DEBUG: 配置文件读取成功
2018-01-17 16:53:19	ewer	everfunc.py - [wrapper]	MainThread - 12080 - 7288	DEBUG: get_notestore 启动运行
2018-01-17 16:53:21	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12080 - 7288	DEBUG: 动用了Evernote API 28 次……
2018-01-17 16:53:21	ewer	everfunc.py - [get_notestore]	MainThread - 12080 - 7288	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:53:22	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12080 - 7288	DEBUG: 动用了Evernote API 29 次……
2018-01-17 16:53:24	ewer	everfunc.py - [writeini]	MainThread - 12080 - 7288	INFO: Evernote API调用次数：30，写入配置文件data\everwork.ini
2018-01-17 16:53:24	ewer	everwork.py - [<module>]	MainThread - 12080 - 7288	DEBUG: 程序结束！
2018-01-17 16:53:50	ewer	everwork.py - [<module>]	MainThread - 2248 - 13244	DEBUG: 程序启动……
2018-01-17 16:53:50	ewer	everwork.py - [<module>]	MainThread - 2248 - 13244	DEBUG: 配置文件读取成功
2018-01-17 16:53:50	ewer	everfunc.py - [wrapper]	MainThread - 2248 - 13244	DEBUG: get_notestore 启动运行
2018-01-17 16:53:52	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2248 - 13244	DEBUG: 动用了Evernote API 30 次……
2018-01-17 16:53:52	ewer	everfunc.py - [get_notestore]	MainThread - 2248 - 13244	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:53:52	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2248 - 13244	DEBUG: 动用了Evernote API 31 次……
2018-01-17 16:53:55	ewer	everfunc.py - [writeini]	MainThread - 2248 - 13244	INFO: Evernote API调用次数：32，写入配置文件data\everwork.ini
2018-01-17 16:53:55	ewer	everwork.py - [<module>]	MainThread - 2248 - 13244	DEBUG: 程序结束！
2018-01-17 16:54:14	ewer	everwork.py - [<module>]	MainThread - 11768 - 1792	DEBUG: 程序启动……
2018-01-17 16:54:14	ewer	everwork.py - [<module>]	MainThread - 11768 - 1792	DEBUG: 配置文件读取成功
2018-01-17 16:54:14	ewer	everfunc.py - [wrapper]	MainThread - 11768 - 1792	DEBUG: get_notestore 启动运行
2018-01-17 16:54:15	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11768 - 1792	DEBUG: 动用了Evernote API 32 次……
2018-01-17 16:54:15	ewer	everfunc.py - [get_notestore]	MainThread - 11768 - 1792	DEBUG: 成功连接Evernote服务器！
2018-01-17 16:54:16	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11768 - 1792	DEBUG: 动用了Evernote API 33 次……
2018-01-17 17:01:20	ewer	everfunc.py - [writeini]	MainThread - 11768 - 1792	INFO: Evernote API调用次数：34，写入配置文件data\everwork.ini
2018-01-17 17:01:20	ewer	everwork.py - [<module>]	MainThread - 11768 - 1792	DEBUG: 程序结束！
2018-01-17 17:01:27	ewer	everwork.py - [<module>]	MainThread - 12892 - 7140	DEBUG: 程序启动……
2018-01-17 17:01:27	ewer	everwork.py - [<module>]	MainThread - 12892 - 7140	DEBUG: 配置文件读取成功
2018-01-17 17:01:27	ewer	everfunc.py - [wrapper]	MainThread - 12892 - 7140	DEBUG: get_notestore 启动运行
2018-01-17 17:01:28	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12892 - 7140	DEBUG: 动用了Evernote API 34 次……
2018-01-17 17:01:28	ewer	everfunc.py - [get_notestore]	MainThread - 12892 - 7140	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:01:29	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12892 - 7140	DEBUG: 动用了Evernote API 35 次……
2018-01-17 17:01:32	ewer	everfunc.py - [writeini]	MainThread - 12892 - 7140	INFO: Evernote API调用次数：36，写入配置文件data\everwork.ini
2018-01-17 17:01:32	ewer	everwork.py - [<module>]	MainThread - 12892 - 7140	DEBUG: 程序结束！
2018-01-17 17:02:36	ewer	everwork.py - [<module>]	MainThread - 10448 - 13060	DEBUG: 程序启动……
2018-01-17 17:02:36	ewer	everwork.py - [<module>]	MainThread - 10448 - 13060	DEBUG: 配置文件读取成功
2018-01-17 17:02:36	ewer	everfunc.py - [wrapper]	MainThread - 10448 - 13060	DEBUG: get_notestore 启动运行
2018-01-17 17:02:38	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10448 - 13060	DEBUG: 动用了Evernote API 36 次……
2018-01-17 17:02:38	ewer	everfunc.py - [get_notestore]	MainThread - 10448 - 13060	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:02:39	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10448 - 13060	DEBUG: 动用了Evernote API 37 次……
2018-01-17 17:02:59	ewer	everfunc.py - [<module>]	MainThread - 5864 - 8568	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 17:02:39,37]
2018-01-17 17:02:59	ewer	everwork.py - [<module>]	MainThread - 5864 - 8568	DEBUG: 程序启动……
2018-01-17 17:02:59	ewer	everwork.py - [<module>]	MainThread - 5864 - 8568	DEBUG: 配置文件读取成功
2018-01-17 17:02:59	ewer	everfunc.py - [wrapper]	MainThread - 5864 - 8568	DEBUG: get_notestore 启动运行
2018-01-17 17:03:00	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5864 - 8568	DEBUG: 动用了Evernote API 38 次……
2018-01-17 17:03:00	ewer	everfunc.py - [get_notestore]	MainThread - 5864 - 8568	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:03:01	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5864 - 8568	DEBUG: 动用了Evernote API 39 次……
2018-01-17 17:03:05	ewer	everfunc.py - [writeini]	MainThread - 5864 - 8568	INFO: Evernote API调用次数：40，写入配置文件data\everwork.ini
2018-01-17 17:03:05	ewer	everwork.py - [<module>]	MainThread - 5864 - 8568	DEBUG: 程序结束！
2018-01-17 17:03:33	ewer	everwork.py - [<module>]	MainThread - 11136 - 9436	DEBUG: 程序启动……
2018-01-17 17:03:33	ewer	everwork.py - [<module>]	MainThread - 11136 - 9436	DEBUG: 配置文件读取成功
2018-01-17 17:03:33	ewer	everfunc.py - [wrapper]	MainThread - 11136 - 9436	DEBUG: get_notestore 启动运行
2018-01-17 17:03:35	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11136 - 9436	DEBUG: 动用了Evernote API 40 次……
2018-01-17 17:03:35	ewer	everfunc.py - [get_notestore]	MainThread - 11136 - 9436	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:03:35	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11136 - 9436	DEBUG: 动用了Evernote API 41 次……
2018-01-17 17:03:37	ewer	everfunc.py - [writeini]	MainThread - 11136 - 9436	INFO: Evernote API调用次数：42，写入配置文件data\everwork.ini
2018-01-17 17:03:37	ewer	everwork.py - [<module>]	MainThread - 11136 - 9436	DEBUG: 程序结束！
2018-01-17 17:05:04	ewer	everwork.py - [<module>]	MainThread - 9368 - 13436	DEBUG: 程序启动……
2018-01-17 17:05:04	ewer	everwork.py - [<module>]	MainThread - 9368 - 13436	DEBUG: 配置文件读取成功
2018-01-17 17:05:04	ewer	everfunc.py - [wrapper]	MainThread - 9368 - 13436	DEBUG: get_notestore 启动运行
2018-01-17 17:05:06	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9368 - 13436	DEBUG: 动用了Evernote API 42 次……
2018-01-17 17:05:06	ewer	everfunc.py - [get_notestore]	MainThread - 9368 - 13436	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:05:06	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9368 - 13436	DEBUG: 动用了Evernote API 43 次……
2018-01-17 17:05:08	ewer	everfunc.py - [writeini]	MainThread - 9368 - 13436	INFO: Evernote API调用次数：44，写入配置文件data\everwork.ini
2018-01-17 17:05:08	ewer	everwork.py - [<module>]	MainThread - 9368 - 13436	DEBUG: 程序结束！
2018-01-17 17:05:19	ewer	everwork.py - [<module>]	MainThread - 14896 - 5736	DEBUG: 程序启动……
2018-01-17 17:05:19	ewer	everwork.py - [<module>]	MainThread - 14896 - 5736	DEBUG: 配置文件读取成功
2018-01-17 17:05:19	ewer	everfunc.py - [wrapper]	MainThread - 14896 - 5736	DEBUG: get_notestore 启动运行
2018-01-17 17:05:21	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14896 - 5736	DEBUG: 动用了Evernote API 44 次……
2018-01-17 17:05:21	ewer	everfunc.py - [get_notestore]	MainThread - 14896 - 5736	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:05:22	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 14896 - 5736	DEBUG: 动用了Evernote API 45 次……
2018-01-17 17:05:24	ewer	everfunc.py - [writeini]	MainThread - 14896 - 5736	INFO: Evernote API调用次数：46，写入配置文件data\everwork.ini
2018-01-17 17:05:24	ewer	everwork.py - [<module>]	MainThread - 14896 - 5736	DEBUG: 程序结束！
2018-01-17 17:07:53	ewer	everwork.py - [<module>]	MainThread - 11184 - 11808	DEBUG: 程序启动……
2018-01-17 17:07:53	ewer	everwork.py - [<module>]	MainThread - 11184 - 11808	DEBUG: 配置文件读取成功
2018-01-17 17:07:53	ewer	everfunc.py - [wrapper]	MainThread - 11184 - 11808	DEBUG: get_notestore 启动运行
2018-01-17 17:07:54	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11184 - 11808	DEBUG: 动用了Evernote API 46 次……
2018-01-17 17:07:54	ewer	everfunc.py - [get_notestore]	MainThread - 11184 - 11808	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:07:55	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 11184 - 11808	DEBUG: 动用了Evernote API 47 次……
2018-01-17 17:08:09	ewer	everfunc.py - [<module>]	MainThread - 7528 - 12872	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 17:07:55,47]
2018-01-17 17:08:09	ewer	everwork.py - [<module>]	MainThread - 7528 - 12872	DEBUG: 程序启动……
2018-01-17 17:08:09	ewer	everwork.py - [<module>]	MainThread - 7528 - 12872	DEBUG: 配置文件读取成功
2018-01-17 17:08:09	ewer	everfunc.py - [wrapper]	MainThread - 7528 - 12872	DEBUG: get_notestore 启动运行
2018-01-17 17:08:10	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 7528 - 12872	DEBUG: 动用了Evernote API 48 次……
2018-01-17 17:08:10	ewer	everfunc.py - [get_notestore]	MainThread - 7528 - 12872	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:08:11	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 7528 - 12872	DEBUG: 动用了Evernote API 49 次……
2018-01-17 17:08:13	ewer	everfunc.py - [writeini]	MainThread - 7528 - 12872	INFO: Evernote API调用次数：50，写入配置文件data\everwork.ini
2018-01-17 17:08:13	ewer	everwork.py - [<module>]	MainThread - 7528 - 12872	DEBUG: 程序结束！
2018-01-17 17:09:11	ewer	everwork.py - [<module>]	MainThread - 6776 - 332	DEBUG: 程序启动……
2018-01-17 17:09:11	ewer	everwork.py - [<module>]	MainThread - 6776 - 332	DEBUG: 配置文件读取成功
2018-01-17 17:09:11	ewer	everfunc.py - [wrapper]	MainThread - 6776 - 332	DEBUG: get_notestore 启动运行
2018-01-17 17:09:13	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 6776 - 332	DEBUG: 动用了Evernote API 50 次……
2018-01-17 17:09:13	ewer	everfunc.py - [get_notestore]	MainThread - 6776 - 332	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:09:13	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 6776 - 332	DEBUG: 动用了Evernote API 51 次……
2018-01-17 17:09:16	ewer	everfunc.py - [writeini]	MainThread - 6776 - 332	INFO: Evernote API调用次数：52，写入配置文件data\everwork.ini
2018-01-17 17:09:16	ewer	everwork.py - [<module>]	MainThread - 6776 - 332	DEBUG: 程序结束！
2018-01-17 17:11:07	ewer	everwork.py - [<module>]	MainThread - 15328 - 6508	DEBUG: 程序启动……
2018-01-17 17:11:07	ewer	everwork.py - [<module>]	MainThread - 15328 - 6508	DEBUG: 配置文件读取成功
2018-01-17 17:11:07	ewer	everfunc.py - [wrapper]	MainThread - 15328 - 6508	DEBUG: get_notestore 启动运行
2018-01-17 17:11:08	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15328 - 6508	DEBUG: 动用了Evernote API 52 次……
2018-01-17 17:11:08	ewer	everfunc.py - [get_notestore]	MainThread - 15328 - 6508	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:11:09	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15328 - 6508	DEBUG: 动用了Evernote API 53 次……
2018-01-17 17:11:12	ewer	everfunc.py - [writeini]	MainThread - 15328 - 6508	INFO: Evernote API调用次数：54，写入配置文件data\everwork.ini
2018-01-17 17:11:12	ewer	everwork.py - [<module>]	MainThread - 15328 - 6508	DEBUG: 程序结束！
2018-01-17 17:11:57	ewer	everwork.py - [<module>]	MainThread - 5964 - 4576	DEBUG: 程序启动……
2018-01-17 17:11:57	ewer	everwork.py - [<module>]	MainThread - 5964 - 4576	DEBUG: 配置文件读取成功
2018-01-17 17:11:57	ewer	everfunc.py - [wrapper]	MainThread - 5964 - 4576	DEBUG: get_notestore 启动运行
2018-01-17 17:11:58	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5964 - 4576	DEBUG: 动用了Evernote API 54 次……
2018-01-17 17:11:58	ewer	everfunc.py - [get_notestore]	MainThread - 5964 - 4576	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:11:59	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5964 - 4576	DEBUG: 动用了Evernote API 55 次……
2018-01-17 17:12:01	ewer	everfunc.py - [writeini]	MainThread - 5964 - 4576	INFO: Evernote API调用次数：56，写入配置文件data\everwork.ini
2018-01-17 17:12:01	ewer	everwork.py - [<module>]	MainThread - 5964 - 4576	DEBUG: 程序结束！
2018-01-17 17:12:35	ewer	everwork.py - [<module>]	MainThread - 9088 - 2248	DEBUG: 程序启动……
2018-01-17 17:12:35	ewer	everwork.py - [<module>]	MainThread - 9088 - 2248	DEBUG: 配置文件读取成功
2018-01-17 17:12:35	ewer	everfunc.py - [wrapper]	MainThread - 9088 - 2248	DEBUG: get_notestore 启动运行
2018-01-17 17:12:36	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9088 - 2248	DEBUG: 动用了Evernote API 56 次……
2018-01-17 17:12:36	ewer	everfunc.py - [get_notestore]	MainThread - 9088 - 2248	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:12:37	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9088 - 2248	DEBUG: 动用了Evernote API 57 次……
2018-01-17 17:12:39	ewer	everfunc.py - [writeini]	MainThread - 9088 - 2248	INFO: Evernote API调用次数：58，写入配置文件data\everwork.ini
2018-01-17 17:12:39	ewer	everwork.py - [<module>]	MainThread - 9088 - 2248	DEBUG: 程序结束！
2018-01-17 17:20:51	ewer	everwork.py - [<module>]	MainThread - 12256 - 15108	DEBUG: 程序启动……
2018-01-17 17:20:51	ewer	everwork.py - [<module>]	MainThread - 12256 - 15108	DEBUG: 配置文件读取成功
2018-01-17 17:20:51	ewer	everfunc.py - [wrapper]	MainThread - 12256 - 15108	DEBUG: get_notestore 启动运行
2018-01-17 17:20:52	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12256 - 15108	DEBUG: 动用了Evernote API 58 次……
2018-01-17 17:20:52	ewer	everfunc.py - [get_notestore]	MainThread - 12256 - 15108	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:20:53	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12256 - 15108	DEBUG: 动用了Evernote API 59 次……
2018-01-17 17:20:55	ewer	everfunc.py - [writeini]	MainThread - 12256 - 15108	INFO: Evernote API调用次数：60，写入配置文件data\everwork.ini
2018-01-17 17:20:55	ewer	everwork.py - [<module>]	MainThread - 12256 - 15108	DEBUG: 程序结束！
2018-01-17 17:21:37	ewer	everwork.py - [<module>]	MainThread - 8380 - 14108	DEBUG: 程序启动……
2018-01-17 17:21:37	ewer	everwork.py - [<module>]	MainThread - 8380 - 14108	DEBUG: 配置文件读取成功
2018-01-17 17:21:37	ewer	everfunc.py - [wrapper]	MainThread - 8380 - 14108	DEBUG: get_notestore 启动运行
2018-01-17 17:21:38	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8380 - 14108	DEBUG: 动用了Evernote API 60 次……
2018-01-17 17:21:38	ewer	everfunc.py - [get_notestore]	MainThread - 8380 - 14108	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:21:39	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8380 - 14108	DEBUG: 动用了Evernote API 61 次……
2018-01-17 17:21:41	ewer	everfunc.py - [writeini]	MainThread - 8380 - 14108	INFO: Evernote API调用次数：62，写入配置文件data\everwork.ini
2018-01-17 17:21:41	ewer	everwork.py - [<module>]	MainThread - 8380 - 14108	DEBUG: 程序结束！
2018-01-17 17:21:58	ewer	everwork.py - [<module>]	MainThread - 10448 - 6960	DEBUG: 程序启动……
2018-01-17 17:21:58	ewer	everwork.py - [<module>]	MainThread - 10448 - 6960	DEBUG: 配置文件读取成功
2018-01-17 17:21:58	ewer	everfunc.py - [wrapper]	MainThread - 10448 - 6960	DEBUG: get_notestore 启动运行
2018-01-17 17:21:59	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10448 - 6960	DEBUG: 动用了Evernote API 62 次……
2018-01-17 17:21:59	ewer	everfunc.py - [get_notestore]	MainThread - 10448 - 6960	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:22:00	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10448 - 6960	DEBUG: 动用了Evernote API 63 次……
2018-01-17 17:22:10	ewer	everfunc.py - [writeini]	MainThread - 10448 - 6960	INFO: Evernote API调用次数：64，写入配置文件data\everwork.ini
2018-01-17 17:22:10	ewer	everwork.py - [<module>]	MainThread - 10448 - 6960	DEBUG: 程序结束！
2018-01-17 17:22:21	ewer	everwork.py - [<module>]	MainThread - 15280 - 5956	DEBUG: 程序启动……
2018-01-17 17:22:21	ewer	everwork.py - [<module>]	MainThread - 15280 - 5956	DEBUG: 配置文件读取成功
2018-01-17 17:22:21	ewer	everfunc.py - [wrapper]	MainThread - 15280 - 5956	DEBUG: get_notestore 启动运行
2018-01-17 17:22:23	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15280 - 5956	DEBUG: 动用了Evernote API 64 次……
2018-01-17 17:22:23	ewer	everfunc.py - [get_notestore]	MainThread - 15280 - 5956	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:22:24	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 15280 - 5956	DEBUG: 动用了Evernote API 65 次……
2018-01-17 17:22:34	ewer	everfunc.py - [writeini]	MainThread - 15280 - 5956	INFO: Evernote API调用次数：66，写入配置文件data\everwork.ini
2018-01-17 17:22:34	ewer	everwork.py - [<module>]	MainThread - 15280 - 5956	DEBUG: 程序结束！
2018-01-17 17:22:46	ewer	everwork.py - [<module>]	MainThread - 2316 - 13236	DEBUG: 程序启动……
2018-01-17 17:22:46	ewer	everwork.py - [<module>]	MainThread - 2316 - 13236	DEBUG: 配置文件读取成功
2018-01-17 17:22:46	ewer	everfunc.py - [wrapper]	MainThread - 2316 - 13236	DEBUG: get_notestore 启动运行
2018-01-17 17:22:48	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2316 - 13236	DEBUG: 动用了Evernote API 66 次……
2018-01-17 17:22:48	ewer	everfunc.py - [get_notestore]	MainThread - 2316 - 13236	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:22:49	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2316 - 13236	DEBUG: 动用了Evernote API 67 次……
2018-01-17 17:22:51	ewer	everfunc.py - [writeini]	MainThread - 2316 - 13236	INFO: Evernote API调用次数：68，写入配置文件data\everwork.ini
2018-01-17 17:22:51	ewer	everwork.py - [<module>]	MainThread - 2316 - 13236	DEBUG: 程序结束！
2018-01-17 17:31:22	ewer	everwork.py - [<module>]	MainThread - 3412 - 5696	DEBUG: 程序启动……
2018-01-17 17:31:22	ewer	everwork.py - [<module>]	MainThread - 3412 - 5696	DEBUG: 配置文件读取成功
2018-01-17 17:31:22	ewer	everfunc.py - [wrapper]	MainThread - 3412 - 5696	DEBUG: get_notestore 启动运行
2018-01-17 17:31:24	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3412 - 5696	DEBUG: 动用了Evernote API 68 次……
2018-01-17 17:31:24	ewer	everfunc.py - [get_notestore]	MainThread - 3412 - 5696	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:31:24	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3412 - 5696	DEBUG: 动用了Evernote API 69 次……
2018-01-17 17:32:02	ewer	everfunc.py - [writeini]	MainThread - 3412 - 5696	INFO: Evernote API调用次数：70，写入配置文件data\everwork.ini
2018-01-17 17:32:02	ewer	everwork.py - [<module>]	MainThread - 3412 - 5696	DEBUG: 程序结束！
2018-01-17 17:32:19	ewer	everwork.py - [<module>]	MainThread - 10164 - 2744	DEBUG: 程序启动……
2018-01-17 17:32:19	ewer	everwork.py - [<module>]	MainThread - 10164 - 2744	DEBUG: 配置文件读取成功
2018-01-17 17:32:19	ewer	everfunc.py - [wrapper]	MainThread - 10164 - 2744	DEBUG: get_notestore 启动运行
2018-01-17 17:32:21	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10164 - 2744	DEBUG: 动用了Evernote API 70 次……
2018-01-17 17:32:21	ewer	everfunc.py - [get_notestore]	MainThread - 10164 - 2744	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:32:21	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10164 - 2744	DEBUG: 动用了Evernote API 71 次……
2018-01-17 17:32:36	ewer	everfunc.py - [writeini]	MainThread - 10164 - 2744	INFO: Evernote API调用次数：72，写入配置文件data\everwork.ini
2018-01-17 17:32:36	ewer	everwork.py - [<module>]	MainThread - 10164 - 2744	DEBUG: 程序结束！
2018-01-17 17:34:12	ewer	everwork.py - [<module>]	MainThread - 4188 - 8868	DEBUG: 程序启动……
2018-01-17 17:34:12	ewer	everwork.py - [<module>]	MainThread - 4188 - 8868	DEBUG: 配置文件读取成功
2018-01-17 17:34:12	ewer	everfunc.py - [wrapper]	MainThread - 4188 - 8868	DEBUG: get_notestore 启动运行
2018-01-17 17:34:14	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 4188 - 8868	DEBUG: 动用了Evernote API 72 次……
2018-01-17 17:34:14	ewer	everfunc.py - [get_notestore]	MainThread - 4188 - 8868	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:34:15	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 4188 - 8868	DEBUG: 动用了Evernote API 73 次……
2018-01-17 17:34:49	ewer	everfunc.py - [writeini]	MainThread - 4188 - 8868	INFO: Evernote API调用次数：74，写入配置文件data\everwork.ini
2018-01-17 17:34:49	ewer	everwork.py - [<module>]	MainThread - 4188 - 8868	DEBUG: 程序结束！
2018-01-17 17:34:54	ewer	everwork.py - [<module>]	MainThread - 13260 - 8092	DEBUG: 程序启动……
2018-01-17 17:34:54	ewer	everwork.py - [<module>]	MainThread - 13260 - 8092	DEBUG: 配置文件读取成功
2018-01-17 17:34:54	ewer	everfunc.py - [wrapper]	MainThread - 13260 - 8092	DEBUG: get_notestore 启动运行
2018-01-17 17:34:56	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13260 - 8092	DEBUG: 动用了Evernote API 74 次……
2018-01-17 17:34:56	ewer	everfunc.py - [get_notestore]	MainThread - 13260 - 8092	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:34:57	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13260 - 8092	DEBUG: 动用了Evernote API 75 次……
2018-01-17 17:35:17	ewer	everfunc.py - [writeini]	MainThread - 13260 - 8092	INFO: Evernote API调用次数：76，写入配置文件data\everwork.ini
2018-01-17 17:35:17	ewer	everwork.py - [<module>]	MainThread - 13260 - 8092	DEBUG: 程序结束！
2018-01-17 17:35:41	ewer	everwork.py - [<module>]	MainThread - 5356 - 2308	DEBUG: 程序启动……
2018-01-17 17:35:41	ewer	everwork.py - [<module>]	MainThread - 5356 - 2308	DEBUG: 配置文件读取成功
2018-01-17 17:35:41	ewer	everfunc.py - [wrapper]	MainThread - 5356 - 2308	DEBUG: get_notestore 启动运行
2018-01-17 17:35:43	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5356 - 2308	DEBUG: 动用了Evernote API 76 次……
2018-01-17 17:35:43	ewer	everfunc.py - [get_notestore]	MainThread - 5356 - 2308	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:35:43	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5356 - 2308	DEBUG: 动用了Evernote API 77 次……
2018-01-17 17:35:47	ewer	everfunc.py - [writeini]	MainThread - 5356 - 2308	INFO: Evernote API调用次数：78，写入配置文件data\everwork.ini
2018-01-17 17:35:47	ewer	everwork.py - [<module>]	MainThread - 5356 - 2308	DEBUG: 程序结束！
2018-01-17 17:36:26	ewer	everwork.py - [<module>]	MainThread - 13692 - 8840	DEBUG: 程序启动……
2018-01-17 17:36:26	ewer	everwork.py - [<module>]	MainThread - 13692 - 8840	DEBUG: 配置文件读取成功
2018-01-17 17:36:26	ewer	everfunc.py - [wrapper]	MainThread - 13692 - 8840	DEBUG: get_notestore 启动运行
2018-01-17 17:36:28	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13692 - 8840	DEBUG: 动用了Evernote API 78 次……
2018-01-17 17:36:28	ewer	everfunc.py - [get_notestore]	MainThread - 13692 - 8840	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:36:28	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 13692 - 8840	DEBUG: 动用了Evernote API 79 次……
2018-01-17 17:37:08	ewer	everfunc.py - [writeini]	MainThread - 13692 - 8840	INFO: Evernote API调用次数：80，写入配置文件data\everwork.ini
2018-01-17 17:37:08	ewer	everwork.py - [<module>]	MainThread - 13692 - 8840	DEBUG: 程序结束！
2018-01-17 17:37:52	ewer	everwork.py - [<module>]	MainThread - 12920 - 3256	DEBUG: 程序启动……
2018-01-17 17:37:52	ewer	everwork.py - [<module>]	MainThread - 12920 - 3256	DEBUG: 配置文件读取成功
2018-01-17 17:37:52	ewer	everfunc.py - [wrapper]	MainThread - 12920 - 3256	DEBUG: get_notestore 启动运行
2018-01-17 17:37:54	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12920 - 3256	DEBUG: 动用了Evernote API 80 次……
2018-01-17 17:37:54	ewer	everfunc.py - [get_notestore]	MainThread - 12920 - 3256	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:37:55	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 12920 - 3256	DEBUG: 动用了Evernote API 81 次……
2018-01-17 17:37:59	ewer	everfunc.py - [writeini]	MainThread - 12920 - 3256	INFO: Evernote API调用次数：82，写入配置文件data\everwork.ini
2018-01-17 17:37:59	ewer	everwork.py - [<module>]	MainThread - 12920 - 3256	DEBUG: 程序结束！
2018-01-17 17:41:44	ewer	everwork.py - [<module>]	MainThread - 3920 - 12000	DEBUG: 程序启动……
2018-01-17 17:41:44	ewer	everwork.py - [<module>]	MainThread - 3920 - 12000	DEBUG: 配置文件读取成功
2018-01-17 17:41:44	ewer	everfunc.py - [wrapper]	MainThread - 3920 - 12000	DEBUG: get_notestore 启动运行
2018-01-17 17:41:46	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3920 - 12000	DEBUG: 动用了Evernote API 82 次……
2018-01-17 17:41:46	ewer	everfunc.py - [get_notestore]	MainThread - 3920 - 12000	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:41:46	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 3920 - 12000	DEBUG: 动用了Evernote API 83 次……
2018-01-17 17:42:26	ewer	everfunc.py - [<module>]	MainThread - 1996 - 1864	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 17:41:46,83]
2018-01-17 17:42:26	ewer	everwork.py - [<module>]	MainThread - 1996 - 1864	DEBUG: 程序启动……
2018-01-17 17:42:26	ewer	everwork.py - [<module>]	MainThread - 1996 - 1864	DEBUG: 配置文件读取成功
2018-01-17 17:42:26	ewer	everfunc.py - [wrapper]	MainThread - 1996 - 1864	DEBUG: get_notestore 启动运行
2018-01-17 17:42:27	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1996 - 1864	DEBUG: 动用了Evernote API 84 次……
2018-01-17 17:42:27	ewer	everfunc.py - [get_notestore]	MainThread - 1996 - 1864	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:42:28	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1996 - 1864	DEBUG: 动用了Evernote API 85 次……
2018-01-17 17:44:43	ewer	everfunc.py - [<module>]	MainThread - 10692 - 9240	INFO: 程序上次异常退出，调用log中的API数据[2018-01-17 17:42:28,85]
2018-01-17 17:44:43	ewer	everwork.py - [<module>]	MainThread - 10692 - 9240	DEBUG: 程序启动……
2018-01-17 17:44:43	ewer	everwork.py - [<module>]	MainThread - 10692 - 9240	DEBUG: 配置文件读取成功
2018-01-17 17:44:43	ewer	everfunc.py - [wrapper]	MainThread - 10692 - 9240	DEBUG: get_notestore 启动运行
2018-01-17 17:44:45	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10692 - 9240	DEBUG: 动用了Evernote API 86 次……
2018-01-17 17:44:45	ewer	everfunc.py - [get_notestore]	MainThread - 10692 - 9240	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:44:46	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 10692 - 9240	DEBUG: 动用了Evernote API 87 次……
2018-01-17 17:44:49	ewer	everfunc.py - [writeini]	MainThread - 10692 - 9240	INFO: Evernote API调用次数：88，写入配置文件data\everwork.ini
2018-01-17 17:44:49	ewer	everwork.py - [<module>]	MainThread - 10692 - 9240	DEBUG: 程序结束！
2018-01-17 17:45:19	ewer	everwork.py - [<module>]	MainThread - 9368 - 9204	DEBUG: 程序启动……
2018-01-17 17:45:19	ewer	everwork.py - [<module>]	MainThread - 9368 - 9204	DEBUG: 配置文件读取成功
2018-01-17 17:45:19	ewer	everfunc.py - [wrapper]	MainThread - 9368 - 9204	DEBUG: get_notestore 启动运行
2018-01-17 17:45:21	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9368 - 9204	DEBUG: 动用了Evernote API 88 次……
2018-01-17 17:45:21	ewer	everfunc.py - [get_notestore]	MainThread - 9368 - 9204	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:45:22	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 9368 - 9204	DEBUG: 动用了Evernote API 89 次……
2018-01-17 17:45:25	ewer	everfunc.py - [writeini]	MainThread - 9368 - 9204	INFO: Evernote API调用次数：90，写入配置文件data\everwork.ini
2018-01-17 17:45:25	ewer	everwork.py - [<module>]	MainThread - 9368 - 9204	DEBUG: 程序结束！
2018-01-17 17:46:37	ewer	everwork.py - [<module>]	MainThread - 5180 - 11952	DEBUG: 程序启动……
2018-01-17 17:46:37	ewer	everwork.py - [<module>]	MainThread - 5180 - 11952	DEBUG: 配置文件读取成功
2018-01-17 17:46:37	ewer	everfunc.py - [wrapper]	MainThread - 5180 - 11952	DEBUG: get_notestore 启动运行
2018-01-17 17:46:38	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5180 - 11952	DEBUG: 动用了Evernote API 90 次……
2018-01-17 17:46:38	ewer	everfunc.py - [get_notestore]	MainThread - 5180 - 11952	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:46:39	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5180 - 11952	DEBUG: 动用了Evernote API 91 次……
2018-01-17 17:46:41	ewer	everfunc.py - [writeini]	MainThread - 5180 - 11952	INFO: Evernote API调用次数：92，写入配置文件data\everwork.ini
2018-01-17 17:46:41	ewer	everwork.py - [<module>]	MainThread - 5180 - 11952	DEBUG: 程序结束！
2018-01-17 17:47:24	ewer	everwork.py - [<module>]	MainThread - 7780 - 6980	DEBUG: 程序启动……
2018-01-17 17:47:24	ewer	everwork.py - [<module>]	MainThread - 7780 - 6980	DEBUG: 配置文件读取成功
2018-01-17 17:47:24	ewer	everfunc.py - [wrapper]	MainThread - 7780 - 6980	DEBUG: get_notestore 启动运行
2018-01-17 17:47:26	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 7780 - 6980	DEBUG: 动用了Evernote API 92 次……
2018-01-17 17:47:26	ewer	everfunc.py - [get_notestore]	MainThread - 7780 - 6980	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:47:26	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 7780 - 6980	DEBUG: 动用了Evernote API 93 次……
2018-01-17 17:47:28	ewer	everfunc.py - [writeini]	MainThread - 7780 - 6980	INFO: Evernote API调用次数：94，写入配置文件data\everwork.ini
2018-01-17 17:47:28	ewer	everwork.py - [<module>]	MainThread - 7780 - 6980	DEBUG: 程序结束！
2018-01-17 17:47:56	ewer	everwork.py - [<module>]	MainThread - 5300 - 11112	DEBUG: 程序启动……
2018-01-17 17:47:56	ewer	everwork.py - [<module>]	MainThread - 5300 - 11112	DEBUG: 配置文件读取成功
2018-01-17 17:47:56	ewer	everfunc.py - [wrapper]	MainThread - 5300 - 11112	DEBUG: get_notestore 启动运行
2018-01-17 17:47:58	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5300 - 11112	DEBUG: 动用了Evernote API 94 次……
2018-01-17 17:47:58	ewer	everfunc.py - [get_notestore]	MainThread - 5300 - 11112	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:47:58	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5300 - 11112	DEBUG: 动用了Evernote API 95 次……
2018-01-17 17:48:01	ewer	everfunc.py - [writeini]	MainThread - 5300 - 11112	INFO: Evernote API调用次数：96，写入配置文件data\everwork.ini
2018-01-17 17:48:01	ewer	everwork.py - [<module>]	MainThread - 5300 - 11112	DEBUG: 程序结束！
2018-01-17 17:49:24	ewer	everwork.py - [<module>]	MainThread - 5096 - 8056	DEBUG: 程序启动……
2018-01-17 17:49:24	ewer	everwork.py - [<module>]	MainThread - 5096 - 8056	DEBUG: 配置文件读取成功
2018-01-17 17:49:24	ewer	everfunc.py - [wrapper]	MainThread - 5096 - 8056	DEBUG: get_notestore 启动运行
2018-01-17 17:49:26	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5096 - 8056	DEBUG: 动用了Evernote API 96 次……
2018-01-17 17:49:26	ewer	everfunc.py - [get_notestore]	MainThread - 5096 - 8056	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:49:27	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 5096 - 8056	DEBUG: 动用了Evernote API 97 次……
2018-01-17 17:49:32	ewer	everfunc.py - [writeini]	MainThread - 5096 - 8056	INFO: Evernote API调用次数：98，写入配置文件data\everwork.ini
2018-01-17 17:49:32	ewer	everwork.py - [<module>]	MainThread - 5096 - 8056	DEBUG: 程序结束！
2018-01-17 17:50:28	ewer	everwork.py - [<module>]	MainThread - 8884 - 15064	DEBUG: 程序启动……
2018-01-17 17:50:28	ewer	everwork.py - [<module>]	MainThread - 8884 - 15064	DEBUG: 配置文件读取成功
2018-01-17 17:50:28	ewer	everfunc.py - [wrapper]	MainThread - 8884 - 15064	DEBUG: get_notestore 启动运行
2018-01-17 17:50:29	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8884 - 15064	DEBUG: 动用了Evernote API 98 次……
2018-01-17 17:50:29	ewer	everfunc.py - [get_notestore]	MainThread - 8884 - 15064	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:50:30	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 8884 - 15064	DEBUG: 动用了Evernote API 99 次……
2018-01-17 17:50:44	ewer	everfunc.py - [writeini]	MainThread - 8884 - 15064	INFO: Evernote API调用次数：100，写入配置文件data\everwork.ini
2018-01-17 17:50:44	ewer	everwork.py - [<module>]	MainThread - 8884 - 15064	DEBUG: 程序结束！
2018-01-17 17:54:28	ewer	everwork.py - [<module>]	MainThread - 2320 - 14500	DEBUG: 程序启动……
2018-01-17 17:54:28	ewer	everwork.py - [<module>]	MainThread - 2320 - 14500	DEBUG: 配置文件读取成功
2018-01-17 17:54:28	ewer	everfunc.py - [wrapper]	MainThread - 2320 - 14500	DEBUG: get_notestore 启动运行
2018-01-17 17:54:30	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2320 - 14500	DEBUG: 动用了Evernote API 100 次……
2018-01-17 17:54:30	ewer	everfunc.py - [get_notestore]	MainThread - 2320 - 14500	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:54:30	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 2320 - 14500	DEBUG: 动用了Evernote API 101 次……
2018-01-17 17:54:30	ewer	everfunc.py - [writeini]	MainThread - 2320 - 14500	INFO: Evernote API调用次数：102，写入配置文件data\everwork.ini
2018-01-17 17:54:30	ewer	everwork.py - [<module>]	MainThread - 2320 - 14500	DEBUG: 程序结束！
2018-01-17 17:56:55	ewer	everwork.py - [<module>]	MainThread - 1452 - 4980	DEBUG: 程序启动……
2018-01-17 17:56:55	ewer	everwork.py - [<module>]	MainThread - 1452 - 4980	DEBUG: 配置文件读取成功
2018-01-17 17:56:55	ewer	everfunc.py - [wrapper]	MainThread - 1452 - 4980	DEBUG: get_notestore 启动运行
2018-01-17 17:56:56	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1452 - 4980	DEBUG: 动用了Evernote API 102 次……
2018-01-17 17:56:56	ewer	everfunc.py - [get_notestore]	MainThread - 1452 - 4980	DEBUG: 成功连接Evernote服务器！
2018-01-17 17:56:57	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1452 - 4980	DEBUG: 动用了Evernote API 103 次……
2018-01-17 17:56:58	ewer	everfunc.py - [evernoteapijiayi]	MainThread - 1452 - 4980	DEBUG: 动用了Evernote API 104 次……
2018-01-17 17:56:58	ewer	everfunc.py - [imglist2note]	MainThread - 1452 - 4980	INFO: 成功更新了笔记《公司进出记录统计图表》，guid：2d908c33-d0a2-4d42-8d4d-5a0bc9d2ff7e。
2018-01-17 17:56:58	ewer	everfunc.py - [writeini]	MainThread - 1452 - 4980	INFO: Evernote API调用次数：105，写入配置文件data\everwork.ini
2018-01-17 17:56:58	ewer	everwork.py - [<module>]	MainThread - 1452 - 4980	DEBUG: 程序结束！
